# code: language=ansible
gitlab01_k8s_applications:
  cnpg:
    enabled: true
    local_volumes:
      cnpg--monitoring--grafana:
        capacity: 10Gi
        path: cnpg/monitoring/grafana
        mode: u=rwx,go=
