- name: Install/Configure GitLab Operator via Helm
  kubernetes.core.helm:
    name: "{{ gitlab.operator.name }}"
    namespace: "{{ gitlab.operator.namespace }}"
    chart_repo_url: "{{ gitlab.operator.url }}"
    chart_version: "{{ gitlab.operator.version }}"
    chart_ref: "{{ gitlab.operator.ref }}"
    release_values: "{{ gitlab.operator.helm_values }}"
    create_namespace: true
    kubeconfig: /etc/kubeconfig
  notify:
    - Wait for GitLab Operator to be Installed

- name: Wait for GitLab Operator to be Installed (flush handlers)
  ansible.builtin.meta: flush_handlers

- name: Create Local Kubernetes Volume Directories
  ansible.builtin.file:
    path: "{{ item.key }}"
    state: directory
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default('root') }}"
    mode: "{{ item.value.mode }}"
  loop: "{{ gitlab.directories | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create GitLab Backup Secret
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: external-backup-s3cfg
        namespace: gitlab-system
      stringData:
        config: |
          host_base = {{ gitlab.backups.minio.base }}
          host_bucket = {{ gitlab.backups.minio.bucket }}
          bucket_location = {{ gitlab.backups.minio.location }}
          use_https = {{ gitlab.backups.minio.https }}
          access_key = {{ gitlab.backups.minio.access }}
          secret_key = {{ gitlab_secrets.backups.minio.key }}
          signature_v2 = False
    kubeconfig: /etc/kubeconfig


# # NOTE: See https://docs.gitlab.com/charts/charts/registry/metadata_database
# - name: Create GitLab Registry PostgreSQL Secret
#   kubernetes.core.k8s:
#     state: present
#     apply: true
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: gitlab-registry-database-password
#         namespace: gitlab-system
#       type: kubernetes.io/basic-auth
#       stringData:
#         username: "{{ gitlab_secrets.registry.postgresql.username }}"
#         password: "{{ gitlab_secrets.registry.postgresql.password }}"
#     kubeconfig: /etc/kubeconfig

- name: Create Local Kubernetes Volume(s) for GitLab
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ item.key }}"
        labels:
          owner: "{{ item.key }}"
      spec:
        capacity:
          storage: "{{ item.value.capacity | default('10Gi') }}"
        accessModes:
          - "{{ item.value.accessMode | default('ReadWriteOnce') }}"
        persistentVolumeReclaimPolicy: "{{ item.value.reclaimPolicy | default('Retain') }}"
        storageClassName: local
        hostPath:
          path: "{{ item.value.path }}"
    kubeconfig: /etc/kubeconfig
  loop: "{{ gitlab.k8s.volumes.local | default({}) |dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create Local Kubernetes Claim(s) for GitLab
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default('gitlab-system') }}"
      spec:
        resources:
          requests:
            storage: "{{ item.value.capacity | default('10Gi') }}"
        accessModes:
          - "{{ item.value.accessMode | default('ReadWriteOnce') }}"
        volumeName: "{{ item.value.volume }}"
        storageClassName: local
    kubeconfig: /etc/kubeconfig
  loop: "{{ gitlab.k8s.claims.local | default({}) |dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Apply GitLab CRD
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: apps.gitlab.com/v1beta1
      kind: GitLab
      metadata:
        name: gitlab
        namespace: gitlab-system
      spec:
        chart:
          version: "{{ gitlab.application.version }}"
          values: "{{ gitlab.application.crd_values }}"
    kubeconfig: /etc/kubeconfig

