- name: GitLab CI Local - Merge Variables
  ansible.builtin.set_fact:
    gitlabci_local_vars: |
      {{ lookup('community.general.merge_variables',
                '_gitlabci_local',
                initial_value=gitlabci_local_defaults,
                pattern_type='suffix') }}

- name: GitLab CI Local - Add Apt Repository
  ansible.builtin.get_url:
    url: "{{ gitlabci_local_vars.apt.repo }}"
    dest: "{{ host.os.package.sources_dir }}/gitlab-ci-local.sources"
    mode: a=r

- name: GitLab CI Local - Update Apt
  ansible.builtin.apt:
    update_cache: true

- name: GitLab CI Local - Install OS packages
  ansible.builtin.package:
    name: "{{ gitlabci_local_vars.packages }}"
