# code: language=ansible
elitedesk_common:
  fqdn: elitedesk.westsidestreet.net
  disk_management:
    disks:
      /dev/sda:
        label: gpt
        force: true
        partitions:
          - number: 1
            size: 100%
            flags: [lvm]

      /dev/sdb:
        label: gpt
        force: true
        partitions:
          - number: 1
            size: 100%
            flags: [lvm]

    volume_groups:
      vg_sda:
        pvs:
          - /dev/sda1
        thinpool: data

      vg_sdb:
        pvs:
          - /dev/sdb1
        thinpool: data

  users_and_groups:
    users:
      claude: "{{ lookup('ansible.builtin.vars', 'global').claude }}"
      hermes: "{{ lookup('ansible.builtin.vars', 'global').hermes }}"
      kerry: "{{ lookup('ansible.builtin.vars', 'global').kerry }}"
      gitlab-runner: "{{ lookup('ansible.builtin.vars', 'global').gitlab_runner }}"
