# dependabot_gitlab:
dependabot_gitlab_disabled:
  k8s:
    claims:
      local:
        gitlab-dependabot-mongodb:
          volume: gitlab-dependabot-mongodb
          capacity: 10Gi
  helm:
    auth:
      enabled: true
    credentials:
      gitlab_access_token: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.glpat.password }}"
    env:
      gitlabUrl: https://gitlab.westsidestreet.net
      logColor: true
    mongodb:
      architecture: standalone
      auth:
        passwords:
          - "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.dependabot.mongodb.password }}"
      persistence:
        existingClaim: gitlab-dependabot-mongodb
    redis:
      auth:
        existingSecret: dependabot--redis
        existingSecretPasswordKey: password
