# code: language=ansible
gitlab_runner:
  helm:
    name: gitlab-runner
    namespace: gitlab-system
    url: https://charts.gitlab.io
    ref: gitlab-runner
    version: 0.75.1
    helm_values:
      gitlabUrl: https://gitlab.westsidestreet.net
      rbac:
        create: true
      runnerToken: "{{ lookup('ansible.builtin.vars', 'gitlab_runner_secrets').token }}"
      runners:
        config: |
          [[runners]]
            [runners.feature_flags]
              FF_ENABLE_BASH_EXIT_CODE_CHECK = true
              FF_SCRIPT_SECTIONS = true
              FF_TIMESTAMPS = true
            [runners.kubernetes]
              image = "registry.westsidestreet.net/kerrys-learning-lab/devsecops/gitlab-runner/gitlab-runner:main"
              privileged = true
              allowed_pull_policies = ["always", "if-not-present"]
              pull_policy = "always"
