# code: language=ansible
elitedesk_gitlab:
  application:
    crd_values:
      global:
        hosts:
          domain: "{{ lookup('ansible.builtin.vars', 'lan').domain }}"
          pages:
            name: "{{ lookup('ansible.builtin.vars', 'lan').hosts.pages }}"
        ingress:
          # Use the Cluster cert-manager (vice the built-in GitLab issuer)
          # See https://docs.gitlab.com/charts/charts/globals/#globalingressconfigurecertmanager
          configureCertmanager: false
          annotations:
            cert-manager.io/issuer: acme-letsencrypt-cluster-issuer
            kubernetes.io/ingress.provider: nginx\
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
            nginx.ingress.kubernetes.io/proxy-connect-timeout: 15
            nginx.ingress.kubernetes.io/proxy-read-timeout: 600
            nginx.ingress.kubernetes.io/service-upstream: true
        appConfig:
          backups:
            bucket: gitlab-backup
            tmpBucket: gitlab-tmp
        kas:
          enabled: true
        pages:
          enabled: true
      gitlab:
        gitaly:
          persistence:
            storageClass: local
            matchLabels:
              owner: gitlab-gitaly
            size: 100Gi
        toolbox:
          backups:
            objectStorage:
              config:
                secret: external-backup-s3cfg
            cron:
              enabled: true
              schedule: "@weekly"
        webservice:
          ingress:
            tls:
              secretName: gitlab-ingress-tls
      gitlab-pages:
        ingress:
          tls:
            secretName: gitlab-pages-tls
      minio:
        ingress:
          tls:
            secretName: gitlab-ingress-tls
      registry:
        enabled: true
        ingress:
          enabled: true
          tls:
            secretName: gitlab-ingress-tls
        database:
          configure: true
          enabled: true
          name: registry
          user: registry
          password:
            secret: gitlab-registry-database-password
            key: password
          migrations:
            enabled: true
      postgresql:
        install: true
        primary:
          persistence:
            existingClaim: postgresql
  k8s:
    claims:
      local:
        # NOTE: Update to GitLab 18.x also required updating Postgres to 16.x
        #       So, changed the name of the PV and the directory
        postgresql:
          volume: gitlab-18.x-postgresql-16.x
          capacity: 100Gi
  backups:
    minio:
      base: nas-minio.westsidestreet.net:9000
      bucket: nas-minio.westsidestreet.net:9000
      location: us-east-1
      https: false
      access: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.backups.minio.access }}"
  certificates:
    gitlab-ingress:
      namespace: gitlab-system
      dnsNames:
        - gitlab.westsidestreet.net
        - registry.westsidestreet.net
        - minio.westsidestreet.net
        - kas.westsidestreet.net
    gitlab-pages:
      namespace: gitlab-system
      dnsNames:
        - pages.westsidestreet.net
        - "*.pages.westsidestreet.net"
  storage:
    local_volumes:
      gitlab-postgresql:
        capacity: 100Gi
        path: gitlab/postgresql
        owner: 1001
        group: 1001
        mode: u=rwx,go=rx
      gitlab-18.x-postgresql-16.x:
        capacity: 100Gi
        path: gitlab-18.x/postgresql-16.x
        owner: 1001
        group: 1001
        mode: u=rwx,go=rx
      gitlab-gitaly:
        capacity: 100Gi
        path: gitlab/gitaly
        owner: 1000
        group: 1000
        mode: u=rwx,go=rx
      gitlab-dependabot-mongodb:
        capacity: 10Gi
        path: gitlab/dependabot/mongodb
        owner: 1001
        group: 0
        mode: u=rwx,go=rx
