k8s_secrets:
  config:
    namespace: infrastructure
    yaml_root: /var/lib/ansible/k8s.d
  string:
    aws:
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ lookup('ansible.builtin.vars', '_secrets').aws.account.username }}"
        password: "{{ lookup('ansible.builtin.vars', '_secrets').aws.account.password }}"
    nas--smb:
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ lookup('ansible.builtin.vars', '_secrets').smb.username }}"
        password: "{{ lookup('ansible.builtin.vars', '_secrets').smb.password }}"
  image_pull:
    - name: registry-westsidestreet.net
      namespace: infrastructure
      auth:
        registry.westsidestreet.net:
          username: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.glpat.username }}"
          password: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.glpat.password }}"
