k8s_certificates:
  argocd-server:
    namespace: gitlab-system
    dnsNames:
      - argocd.westsidestreet.net
  gitlab-ingress:
    namespace: gitlab-system
    dnsNames:
      - gitlab.westsidestreet.net
      - registry.westsidestreet.net
      - minio.westsidestreet.net
      - kas.westsidestreet.net
  # mlflow:
  #   dnsNames:
  #     - mlflow.westsidestreet.net
  # nas:
  #   namespace: infrastructure
  #   dnsNames:
  #     - nas.westsidestreet.net
  #     - nas-minio.westsidestreet.net
  #     - nas-registry.westsidestreet.net
  #     - ephemeral-registry.westsidestreet.net
