# code: language=ansible
k8s_secrets:
  config:
    namespace: infrastructure
    yaml_root: /var/lib/ansible/k8s.d
  string:
    aws:
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ lookup('ansible.builtin.vars', '_secrets').aws.account.username }}"
        password: "{{ lookup('ansible.builtin.vars', '_secrets').aws.account.password }}"
    nas--smb:
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ lookup('ansible.builtin.vars', '_secrets').smb.username }}"
        password: "{{ lookup('ansible.builtin.vars', '_secrets').smb.password }}"
    dependabot--mongodb:
      namespace: gitlab-system
      stringData:
        mongodb-root-password: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.dependabot.mongodb.password }}"
    dependabot--redis:
      type: kubernetes.io/basic-auth
      namespace: gitlab-system
      stringData:
        username: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.dependabot.redis.username }}"
        password: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.dependabot.redis.password }}"
