k8s_local_volumes:
  # --- GitLab
  gitlab-postgresql:
    capacity: 100Gi
    path: gitlab/postgresql
    owner: 1001
    group: 1001
    mode: u=rwx,go=rx
  gitlab-gitaly:
    capacity: 100Gi
    path: gitlab/gitaly
    owner: 1000
    group: 1000
    mode: u=rwx,go=rx
  gitlab-dependabot-mongodb:
    capacity: 10Gi
    path: gitlab/dependabot/mongodb
    owner: 1001
    group: 0
    mode: u=rwx,go=rx



  # --- MLFlow
  mlflow-postgresql:
    capacity: 100Gi
    path: mlflow/postgresql
    owner: 999
    group: 999
    mode: ug=rwx,o=rx
