# code: language=ansible
elitedesk_k8s:

  certificates:
    argocd-server:
      namespace: gitlab-system
      dnsNames:
        - argocd.westsidestreet.net
    gitlab-ingress:
      namespace: gitlab-system
      dnsNames:
        - gitlab.westsidestreet.net
        - registry.westsidestreet.net
        - minio.westsidestreet.net
        - kas.westsidestreet.net

  metallb:
    pool:
      # NOTE: Reserved these in the Netgear router by setting the upper
      #       limit of the router's IP range to a.b.c.199
      - 192.168.0.235-192.168.0.244

  storage:
    local_volumes:
      # --- GitLab
      gitlab-postgresql:
        capacity: 100Gi
        path: gitlab/postgresql
        owner: 1001
        group: 1001
        mode: u=rwx,go=rx
      gitlab-18.x-postgresql-16.x:
        capacity: 100Gi
        path: gitlab-18.x/postgresql-16.x
        owner: 1001
        group: 1001
        mode: u=rwx,go=rx
      gitlab-gitaly:
        capacity: 100Gi
        path: gitlab/gitaly
        owner: 1000
        group: 1000
        mode: u=rwx,go=rx
      gitlab-dependabot-mongodb:
        capacity: 10Gi
        path: gitlab/dependabot/mongodb
        owner: 1001
        group: 0
        mode: u=rwx,go=rx

      # --- MLFlow
      mlflow-postgresql:
        capacity: 100Gi
        path: mlflow/postgresql
        owner: 999
        group: 999
        mode: ug=rwx,o=rx

  secrets:
    aws:
      type: kubernetes.io/basic-auth
      namespace: infrastructure
      stringData:
        username: "{{ lookup('ansible.builtin.vars', 'secrets_vault').aws.account.username }}"
        password: "{{ lookup('ansible.builtin.vars', 'secrets_vault').aws.account.password }}"
    nas--smb:
      type: kubernetes.io/basic-auth
      namespace: infrastructure
      stringData:
        username: "{{ lookup('ansible.builtin.vars', 'secrets_vault').smb.username }}"
        password: "{{ lookup('ansible.builtin.vars', 'secrets_vault').smb.password }}"
