host:
  packages:
    - ntfs-3g
  argocd:
    helm_values:
      global:
        domain: argocd.westsidestreet.net
      server:
        ingress:
          enabled: true
          tls: true
          ingressClassName: gitlab-nginx
        service:
          type: LoadBalancer

  mounts: {}
  k8s:
    namespaces:
      - mlflow

ansible_fqdn: elitedesk.westsidestreet.net
ansible_host: elitedesk.westsidestreet.net
