# code: language=ansible
host:
  packages:
    - ntfs-3g
  argocd:
    helm_values:
      global:
        domain: "{{ lookup('ansible.builtin.vars', 'lan').hosts.argocd }}"
      server:
        ingress:
          enabled: true
          tls: true
          ingressClassName: gitlab-nginx
        service:
          type: LoadBalancer

  mounts: {}
  k8s:
    namespaces:
      - mlflow

ansible_fqdn: elitedesk.westsidestreet.net
ansible_host: elitedesk.westsidestreet.net
