host:
  packages:
    - ntfs-3g
  argocd:
    helm_values:
      global:
        domain: argocd.westsidestreet.net
      server:
        ingress:
          enabled: true
          tls: true
          ingressClassName: gitlab-nginx
        service:
          type: LoadBalancer

  mounts: {}
  metal:
    # NOTE: Reserved these in the Netgear router by setting the upper
    #       limit of the router's IP range to a.b.c.199
    pool: 192.168.0.235-192.168.0.244
  k8s:
    namespaces:
      - mlflow

fqdn: elitdesk.westsidestreet.net
