# code: language=ansible
# NOTE: I never ended up using MLFlow (using GitLab instead)
mlflow_k8s:
  # certificates:
  #   mlflow:
  #     dnsNames:
  #       - mlflow.westsidestreet.net

  storage:
    local_volumes:
      mlflow-postgresql:
        capacity: 100Gi
        path: mlflow/postgresql
        owner: 999
        group: 999
        mode: ug=rwx,o=rx
