# code: language=ansible
# Prerequisites:
# curl -sfL https://get.rke2.io | sudo sh -
# Reference: https://docs.rke2.io/install/quickstart
elitedesk_rke2:
  tls-san:
    - elitedesk
    - elitedesk.westsidestreet.net
    - 192.168.0.159
