- name: Create Kubernetes Secrets
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: "{{ item.value.type | default('Opaque') }}"
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default('infrastructure') | lower }}"
      stringData: "{{ item.value.stringData }}"
    kubeconfig: /etc/kubeconfig
  when: "'stringData' in item.value"
  loop: "{{ secrets.k8s | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
