# code: language=ansible
{% if 'server' in rke2_vars %}
server: "{{ rke2_vars['server'] }}"
token: "{{ rke2_vars['token'] }}"
{% endif %}
write-kubeconfig-mode: "0644"
advertise-address: "{{ rke2_vars.address | default(ansible_default_ipv4.address) }}"
{% if 'tls-san' in rke2_vars %}
tls-san:
  {% for san in rke2_vars['tls-san'] %}
  - "{{ san }}"
  {% endfor %}
{% endif %}
