include:
  - component: $GITLABCI_COMPONENT_CATALOG_PROJECT/ansible-playbook.pipeline@$GITLABCI_COMPONENT_CATALOG_REF
    inputs:
      ansible_file: westsidestreet.net.yaml
      ansible_requirements_file: collections/requirements.yaml
      ansible_inventory_path: inventory
      # Can't trust that my Asus laptop is on/available when CI/CD runs
      ansible_host_filter: "all:!asus"
