# code: language=ansible
- name: Bootstrap the Ansible Host
  become: true
  pre_tasks:
    - name: Setup Ansible facts
      ansible.builtin.setup:
      tags:
        - always
  hosts:
    - ansible
  roles:
    - role: kerrys_learning_lab.base.ansible
  tags:
    - ansible

- name: Common Configuration for all Linux Hosts
  become: true
  pre_tasks:
    - name: Setup Ansible facts
      ansible.builtin.setup:
      tags:
        - always
  hosts:
    - all
  roles:
    - role: kerrys_learning_lab.base.common
  tags:
    - common
  any_errors_fatal: true

- name: Proxmox VE Host Configuration
  become: true
  hosts:
    - proxmox
  pre_tasks:
    - name: Setup Ansible facts
      ansible.builtin.setup:
      tags:
        - always
  roles:
    - role: proxmox
  tags:
    - proxmox
  any_errors_fatal: true

- name: GPU Drivers and Services
  become: true
  hosts:
    - nvidia
  pre_tasks:
    - name: Setup Ansible facts
      ansible.builtin.setup:
      tags:
        - always
  roles:
    - role: kerrys_learning_lab.base.nvidia
      tags:
        - gpu
        - nvidia

- name: Install/Configure Kubernetes and Kubernetes Applications
  become: true
  hosts: k8s
  pre_tasks:
    - name: Setup Ansible facts
      ansible.builtin.setup:
      tags:
        - always
  roles:
    - role: kerrys_learning_lab.kubernetes.k8s_engine
      tags:
        - k8s-engine
    - role: kerrys_learning_lab.kubernetes.k8s_tools
      tags:
        - k8s-tools
    - role: kerrys_learning_lab.kubernetes.k8s_ecosystem
      tags:
        - k8s-ecosystem
    - role: kerrys_learning_lab.kubernetes.k8s_applications
      tags:
        - k8s-applications
    - role: kerrys_learning_lab.kubernetes.k8s_share
      tags:
        - share
    - role: kerrys_learning_lab.kubernetes.argocd
      when: "'argocd' in group_names"
      tags:
        - argocd
    - role: gitlab
      when: "'gitlab' in group_names"
      tags:
        - gitlab
    - role: gitlab-runner
      when: "'gitlab_runner' in group_names"
      tags:
        - gitlab
        - gitlab-runner
  tags:
    - k8s
    - kubernetes

- name: Configure for Development
  become: true
  hosts:
    - development
  pre_tasks:
    - name: Setup Ansible facts
      ansible.builtin.setup:
      tags:
        - always
  roles:
    - role: dev-tools
  tags:
    - dev-tools
  any_errors_fatal: true
