# code: language=ansible
- name: Create K8s Local Share Directories - {{ _ansible_host }}
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ k8s_share_vars.inherited.owner }}"
    group: "{{ k8s_share_vars.inherited.group }}"
    mode: "{{ k8s_share_vars.inherited.mode }}"
  loop:
    - "{{ k8s_share_vars.inherited.downloads }}"
    - "{{ k8s_share_vars.inherited.share }}/kubeconfig.d"
  delegate_to: "{{ _ansible_host }}"
