# code: language=ansible
- name: Merge K8S Share Variables
  ansible.builtin.set_fact:
    k8s_share_vars: |
      {{ lookup('community.general.merge_variables',
                '_k8s_share',
                initial_value=k8s_share_defaults,
                pattern_type='suffix') }}

- name: Create K8s Local Share Directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ k8s_share_vars.role.owner }}"
    group: "{{ k8s_share_vars.role.group }}"
    mode: "{{ k8s_share_vars.role.mode }}"
  loop:
    - "{{ k8s_share_vars.role.downloads }}"
    - "{{ k8s_share_vars.role.share }}"
  delegate_to: localhost

- name: Fetch All Kubeconfigs
  ansible.builtin.slurp:
    src: "{{ k8s_share_vars.role.kubeconfig }}"
  register: k8s_share_fetched_kubeconfigs

- name: Write Kubeconfig Locally
  ansible.builtin.copy:
    content: "{{ k8s_share_fetched_kubeconfigs.content | b64decode }}"
    dest: "{{ k8s_share_vars.role.downloads }}/kubeconfig.{{ inventory_hostname }}-loopback.yaml"
    owner: "{{ k8s_share_vars.role.owner }}"
    group: "{{ k8s_share_vars.role.group }}"
    mode: "{{ k8s_share_vars.role.mode }}"
  delegate_to: localhost

- name: Transform and Share Kubeconfig
  kubeconfig_transform:
    src: "{{ k8s_share_vars.role.downloads }}/kubeconfig.{{ inventory_hostname }}-loopback.yaml"
    dest: "{{ k8s_share_vars.role.share }}/kubeconfig.{{ inventory_hostname }}.yaml"
    server: "{{ ansible_fqdn }}"
    name: "{{ inventory_hostname }}"
    owner: "{{ k8s_share_vars.role.owner }}"
    group: "{{ k8s_share_vars.role.group }}"
    mode: "{{ k8s_share_vars.role.mode }}"
  delegate_to: localhost
