# code: language=ansible
- name: Set Elasticsearch Operator Base Facts
  ansible.builtin.set_fact:
    elasticsearch_operator_version: "{{ elasticsearch_operator.version | default(elasticsearch_operator_defaults.version) }}"
    elasticsearch_operator_url_prefix: "{{ elasticsearch_operator.url.prefix | default(elasticsearch_operator_defaults.url.prefix) }}"

- name: Set Elasticsearch Operator Derived Facts
  ansible.builtin.set_fact:
    elasticsearch_operator_crds_url: "{{ elasticsearch_operator_url_prefix }}/{{ elasticsearch_operator_version }}/crds.yaml"
    elasticsearch_operator_operator_url: "{{ elasticsearch_operator_url_prefix }}/{{ elasticsearch_operator_version }}/operator.yaml"

- name: Install Elasticsearch CRDs
  kubernetes.core.k8s:
    state: present
    apply: true
    src: "{{ elasticsearch_operator_crds_url }}"
    kubeconfig: /etc/kubeconfig

- name: Install Elasticsearch Operator
  kubernetes.core.k8s:
    state: present
    apply: true
    src: "{{ elasticsearch_operator_operator_url }}"
    kubeconfig: /etc/kubeconfig
