# code: language=ansible
#
# GitLab Role Defaults
#
# These values can be overridden per-group or per-host using the Variable
# Merge Pattern.  For example, to override for elitedesk, create a variable
# named `elitedesk_gitlab` in `host_vars/elitedesk/gitlab.yaml`.
#
# Global values (owner, group, mode, kubeconfig, etc.) can be changed for
# all roles by updating `group_vars/all/global.yaml`.
#
gitlab_defaults:

  inherited:
    owner: "{{ lookup('ansible.builtin.vars', 'global').owner | default('root') }}"
    group: "{{ lookup('ansible.builtin.vars', 'global').group | default('root') }}"
    mode: "{{ lookup('ansible.builtin.vars', 'global').mode | default('a=rX') }}"
    working: "{{ lookup('ansible.builtin.vars', 'global').working | default('/var/lib/ansible') }}/{{ role_name }}"
    kubeconfig: "{{ lookup('ansible.builtin.vars', 'global').kubeconfig | default('/etc/kubeconfig') }}"
    local_volumes: /var/lib/k8s-local-volumes

  operator:
    name: gitlab-ci
    namespace: gitlab-system
    url: https://charts.gitlab.io
    ref: gitlab-operator
    # renovate: datasource=helm registryUrl=https://charts.gitlab.io depName=gitlab-operator
    version: 3.0.2
    helm_values: {}

  application:
    name: gitlab
    # renovate: datasource=helm registryUrl=https://charts.gitlab.io depName=gitlab
    version: 10.1.1
    crd_values: {}

  cluster_cert_issuer:
    name: acme-letsencrypt-cluster-issuer
    kind: ClusterIssuer

  certificates: {}

  storage:
    local_volumes: {}

  k8s:
    claims:
      local: {}

  backups:
    minio: {}
