# code: language=ansible
common_defaults:

  # --------------------------------------------------------------------------
  # OS Packages
  packages:
    - bash-completion
    - cifs-utils
    - curl
    - gnupg2
    - traceroute
    - tree
    - vim

    # Required for Ansible remote execution
    - python3-kubernetes

    # Required for automated disk management
    - lvm2
    - parted
    - python3-parted


  # --------------------------------------------------------------------------
  # OS Settings
  settings:
    timezone: America/Denver
    sysctl:
      # These were needed by k8s.. should they move to a k8s role??
      fs.inotify.max_user_watches: 524288
      fs.inotify.max_user_instances: 524288
      fs.inotify.max_queued_events: 524288


  # --------------------------------------------------------------------------
  # Name resolution
  resolve:
    nameservers: []
    hosts: {}
    resolvectl: /usr/bin/resolvectl


  # --------------------------------------------------------------------------
  users_and_groups:
    users: {}
    groups: []

  # --------------------------------------------------------------------------
  # Disk Management (partitions, LVM, filesystems, mounts)
  disk_management:
    disks: {}
    volume_groups: {}

  inherited:
    owner: "{{ lookup('ansible.builtin.vars', 'global').owner | default('root') }}"
    group: "{{ lookup('ansible.builtin.vars', 'global').group | default('root') }}"
    mode: "{{ lookup('ansible.builtin.vars', 'global').mode | default('a=rX') }}"
    downloads: "{{ lookup('ansible.builtin.vars', 'global').working | default('/var/lib/ansible') }}/downloads"
    facts: "{{ lookup('ansible.builtin.vars', 'global').facts | default('/etc/ansible/facts.d') }}"
    install: "{{ lookup('ansible.builtin.vars', 'global').install | default('/usr/local/install') }}"
    source: "{{ lookup('ansible.builtin.vars', 'global').source | default('/usr/local/src') }}"
    secrets: "{{ lookup('ansible.builtin.vars', 'global').secrets | default('/usr/local/secrets') }}"
