# Override k8s_engine group_vars — cloud GPU doesn't need metallb or SMB
cloud_gpu_k8s_engine:
  engine: k3s
  needs:
    cert_manager: true
    smb_driver: false
    metallb: false
  kubeconfig: /etc/rancher/k3s/k3s.yaml
  service: k3s
  k3s:
    tls-san:
      - cloud-gpu.westsidestreet.net
