# code: language=ansible
cloudgpu_k8s_ecosystem:

  metallb:
    pool: []

  storage:
    classes: {}
    local_volumes:
      cloud-lab-inference--vllm-storage:
        path: cloud-lab/cloud-gpu/vllm/data
        capacity: 50Gi


  cluster_cert_issuer:
    name: acme-letsencrypt-cluster-issuer
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: kerry.t.johnson@gmail.com
        privateKeySecretRef:
          name: acme-letsencrypt-cluster-issuer
        solvers:
          - http01:
              ingress:
                class: traefik
