# code: language=ansible
ansible_fqdn: cloud-gpu.westsidestreet.net
ansible_host: 54.186.253.30
ansible_user: ubuntu

# Override k8s_engine group_vars — cloud GPU doesn't need metallb or SMB
k8s_engine:
  engine: k3s
  needs:
    cert_manager: true
    smb_driver: false
    metallb: false
  kubeconfig: /etc/rancher/k3s/k3s.yaml
  service: k3s
