# code: language=ansible
asus_common:
  fqdn: asus.westsidestreet.net
  resolve:
    link: 3
  packages:
    - shotwell # Image editor
    - zsh
  users_and_groups:
    users:
      claude: "{{ lookup('ansible.builtin.vars', 'global').claude }}"
      kerry: "{{ lookup('ansible.builtin.vars', 'global').kerry }}"
      gitlab-runner: "{{ lookup('ansible.builtin.vars', 'global').gitlab_runner }}"

      # Strictly speaking, it's not necessary to have an account for ArgoCD.
      # But, it's a convenient place to control its SSH keys and use for
      # trouble-shooting access to (e.g.) GitLab
      argo:
        name: Argo
        email: argo@westsidestreet.net
        create: true
        shell: /bin/bash
        ssh_key:
          public: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILMedk4rvJpujyrRHDSMQfQNE+IHVkL5tDynFLMrbbGC argo@westsidestreet.net
          private: "{{ lookup('ansible.builtin.vars', 'secrets_vault').argocd.ed25519 }}"
        chezmoi: {}
