# code: language=ansible
asus_k8s_applications:
  elastic_operator:
    enabled: true
  helm:
    nats:
      namespace: dev
      chart:
        url: https://nats-io.github.io/k8s/helm/charts
        version: 2.12.4
        ref: nats
      helm_values:
        config:
          merge:
            debug: true
            trace: true
            logtime: true
          jetstream:
            enabled: true
            fileStore:
              pvc:
                size: 10Gi
            memoryStore:
              enabled: true
              maxSize: 2Gi
