# code: language=ansible
asus_k8s_ecosystem:
  namespaces:
    - boids
    - dev

  certificates:
    boids-dev:
      namespace: boids
      dnsNames:
        - boids-dev.westsidestreet.net

  metallb:
    pool:
      # NOTE: Reserved these in the Netgear router by setting the upper
      #       limit of the router's IP range to a.b.c.199
      - 192.168.0.225-192.168.0.229

  storage:
    local_volumes:
      oracle--agentic--sandbox--oracle-db:
        capacity: 10Gi
        path: oracle/agentic/sandbox/oracle-db
        mode: u=rwx,go=
