dev:
  hosts:
    wsl:
      ansible_connection: local

gitlab:
  hosts:
    elitedesk:
      ansible_host: elitedesk.westsidestreet.net

argocd:
  hosts:
    elitedesk:
      ansible_host: elitedesk.westsidestreet.net

clusters:
  hosts:
    elitedesk:
    raspberrypi4-01: # All Pis are combined in a single cluster!
    wsl:

raspberry_pi:
  hosts:
    raspberrypi5-01:
    raspberrypi5-02:
    raspberrypi4-01:
