all:
  hosts:
    asus:
    elitedesk:
    gitlab01:
    nvidia-5080:

ansible:
  hosts:
    asus:

argocd:
  children:
    argocd_server:
      hosts:
        gitlab01:
    argocd_cluster:
      hosts:
        gitlab01:
        asus:
        nvidia-5080:

development:
  hosts:
    asus:

gitlab:
  hosts:
    gitlab01:

gitlab_runner:
  hosts:
    gitlab01:
    nvidia-5080:

gpu:
  children:
    nvidia:
      hosts:
        asus:
        nvidia-5080:

proxmox:
  hosts:
    elitedesk:

k8s:
  children:
    k8s_engine_crc:
      hosts:
    k8s_engine_k3s:
      hosts:
        asus:
        gitlab01:
        nvidia-5080:

raspberry_pi:
  hosts: {}
    # raspberrypi5-01:
    # raspberrypi5-02:
    # raspberrypi4-01:

ubuntu:
  hosts:
    asus:
    gitlab01:
    nvidia-5080:
