all:
  hosts:
    asus:
    nvidia-5080:

development:
  hosts:
    asus:
    nvidia-5080:

k8s:
  hosts:
    asus:
    elitedesk:
    nvidia-5080:

gitlab:
  hosts:
    elitedesk:

mlflow:
  hosts:
    elitedesk:

argocd:
  hosts:
    elitedesk:

raspberry_pi:
  hosts:
    # raspberrypi5-01:
    # raspberrypi5-02:
    # raspberrypi4-01:
