apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ appset_name }}
  namespace: {{ argocd_vars.namespace }}
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
{% if appset_type == 'helm-chart' %}
    - git:
        repoURL: {{ appset.source.url }}
        revision: {{ appset.source.ref }}
        files:
          - path: {{ appset.source.path }}/*/chart.yaml
{% elif appset_type == 'git-repo' %}
    - git:
        repoURL: {{ appset.source.url }}
        revision: {{ appset.source.ref }}
        files:
          - path: {{ appset.source.path }}/*/repo.yaml
{% elif appset_type == 'matrix-chart' %}
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env/{{ appset_key }}: "true"
          - git:
              repoURL: {{ appset.source.url }}
              revision: {{ appset.source.ref }}
              files:
                - path: "{{ appset_key }}/*/*/chart.yaml"
{% elif appset_type == 'matrix-repo' %}
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env/{{ appset_key }}: "true"
          - git:
              repoURL: {{ appset.source.url }}
              revision: {{ appset.source.ref }}
              files:
                - path: "{{ appset_key }}/*/*/repo.yaml"
{% endif %}
  template:
    metadata:
{% if appset_type in ['matrix-chart', 'matrix-repo'] %}
      name: "{{ '{{' }} .name {{ '}}' }}-{{ '{{' }} index .path.segments 1 {{ '}}' }}-{{ '{{' }} index .path.segments 2 {{ '}}' }}"
{% else %}
      name: "{{ appset_key }}-{{ '{{' }} index .path.segments 1 {{ '}}' }}"
{% endif %}
    spec:
{% if appset_type in ['matrix-chart', 'matrix-repo'] %}
      project: "{{ '{{' }} index .path.segments 1 {{ '}}' }}"
{% else %}
      project: {{ appset_key }}
{% endif %}
      sources:
{% if appset_type == 'helm-chart' %}
        - repoURL: "{{ '{{' }} .source.repoURL {{ '}}' }}"
          targetRevision: "{{ '{{' }} .source.targetRevision {{ '}}' }}"
          chart: "{{ '{{' }} .source.chart {{ '}}' }}"
          helm:
            valueFiles:
              - "$values/{{ appset.source.path }}/{{ '{{' }} index .path.segments 1 {{ '}}' }}/values.yaml"
        - repoURL: {{ appset.source.url }}
          targetRevision: {{ appset.source.ref }}
          ref: values
{% elif appset_type == 'git-repo' %}
        - repoURL: "{{ '{{' }} .source.repoURL {{ '}}' }}"
          targetRevision: "{{ '{{' }} .source.targetRevision {{ '}}' }}"
          path: "{{ '{{' }} .source.path {{ '}}' }}"
          helm:
            valueFiles:
              - "$values/{{ appset.source.path }}/{{ '{{' }} index .path.segments 1 {{ '}}' }}/values.yaml"
        - repoURL: {{ appset.source.url }}
          targetRevision: {{ appset.source.ref }}
          ref: values
{% elif appset_type == 'matrix-chart' %}
        - repoURL: "{{ '{{' }} .source.repoURL {{ '}}' }}"
          targetRevision: "{{ '{{' }} .source.targetRevision {{ '}}' }}"
          chart: "{{ '{{' }} .source.chart {{ '}}' }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$values/{{ appset_key }}/{{ '{{' }} index .path.segments 1 {{ '}}' }}/{{ '{{' }} index .path.segments 2 {{ '}}' }}/values.yaml"
              - "$values/{{ appset_key }}/{{ '{{' }} index .path.segments 1 {{ '}}' }}/{{ '{{' }} index .path.segments 2 {{ '}}' }}/{{ '{{' }} .name {{ '}}' }}-values.yaml"
        - repoURL: {{ appset.source.url }}
          targetRevision: {{ appset.source.ref }}
          ref: values
{% elif appset_type == 'matrix-repo' %}
        - repoURL: "{{ '{{' }} .source.repoURL {{ '}}' }}"
          targetRevision: "{{ '{{' }} .source.targetRevision {{ '}}' }}"
          path: "{{ '{{' }} .source.path {{ '}}' }}"
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
              - "$values/{{ appset_key }}/{{ '{{' }} index .path.segments 1 {{ '}}' }}/{{ '{{' }} index .path.segments 2 {{ '}}' }}/values.yaml"
              - "$values/{{ appset_key }}/{{ '{{' }} index .path.segments 1 {{ '}}' }}/{{ '{{' }} index .path.segments 2 {{ '}}' }}/{{ '{{' }} .name {{ '}}' }}-values.yaml"
        - repoURL: {{ appset.source.url }}
          targetRevision: {{ appset.source.ref }}
          ref: values
{% endif %}
      destination:
{% if appset_type in ['matrix-chart', 'matrix-repo'] %}
        name: "{{ '{{' }} .name {{ '}}' }}"
        namespace: "{{ '{{' }} index .path.segments 1 {{ '}}' }}"
{% else %}
        name: {{ appset.destination.name }}
        namespace: {{ appset.destination.namespace | default(appset_key) }}
{% endif %}
      syncPolicy:
        automated:
          prune: {{ (appset.automatedSync | default({})).prune | default(True) }}
          selfHeal: {{ (appset.automatedSync | default({})).selfHeal | default(True) }}
        syncOptions:
          - CreateNamespace=true
