# code: language=ansible
k8s_ecosystem_defaults:

  cert_manager:
    chart:
      url: https://charts.jetstack.io
      # renovate: datasource=helm registryUrl=https://charts.jetstack.io depName=cert-manager
      version: v1.20.0
    helm_values:
      crds:
        enabled: true
      # # dns01RecursiveNameservers: 192.168.0.3:53
      # dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53
      # dns01RecursiveNameserversOnly: true


  certificates: {}


  cluster_cert_issuer: {}

  sealed_secrets:
    chart:
      url: https://bitnami-labs.github.io/sealed-secrets
      ref: sealed-secrets
      # renovate: datasource=helm registryUrl=https://bitnami-labs.github.io/sealed-secrets depName=sealed-secrets
      version: 2.18.4
    helm_values:
      # OpenShift's Security Context Constraints (SCCs) require pods to run
      # with a dynamically assigned user ID (UID) and group ID (GID) range
      # rather than a fixed value like root/0
      podSecurityContext:
        fsGroup: null

      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsUser: null
        seccompProfile:
          type: RuntimeDefault


  namespaces: []


  secrets: {}


  metallb:
    chart:
      url: https://metallb.github.io/metallb
      ref: metallb
      # renovate: datasource=helm registryUrl=https://metallb.github.io/metallb depName=metallb
      version: 0.15.3
      helm_values:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
    pool: []


  smb_driver:
    chart:
      url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      ref: csi-driver-smb
      # renovate: datasource=helm registryUrl=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts depName=csi-driver-smb
      version: 1.20.1
    helm_values: {}


  storage:
    classes:
      smb:
        provisioner: smb.csi.k8s.io
        parameters:
          source: //{{ lookup('ansible.builtin.vars', 'lan').ip.smb }}/kubernetes
          subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
          csi.storage.k8s.io/provisioner-secret-name: nas--smb
          csi.storage.k8s.io/provisioner-secret-namespace: infrastructure
          csi.storage.k8s.io/node-stage-secret-name: nas--smb
          csi.storage.k8s.io/node-stage-secret-namespace: infrastructure
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
          - uid=0
          - gid=0
          - noperm
          - mfsymlinks
          - cache=strict
          - noserverino  # required to prevent data corruption

      local:
        provisioner: kubernetes.io/no-provisioner
        volumeBindingMode: WaitForFirstConsumer
        reclaimPolicy: Retain
        allowVolumeExpansion: false

      # Added host name to the path
      smb-2025-11-01:
        provisioner: smb.csi.k8s.io
        default: "true"
        parameters:
          source: //{{ lookup('ansible.builtin.vars', 'lan').ip.smb }}/kubernetes
          subDir: "{{ inventory_hostname }}/${pvc.metadata.namespace}/${pvc.metadata.name}"
          csi.storage.k8s.io/provisioner-secret-name: nas--smb
          csi.storage.k8s.io/provisioner-secret-namespace: infrastructure
          csi.storage.k8s.io/node-stage-secret-name: nas--smb
          csi.storage.k8s.io/node-stage-secret-namespace: infrastructure
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        mountOptions:
          - dir_mode=0777
          - file_mode=0777
          - uid=0
          - gid=0
          - noperm
          - mfsymlinks
          - cache=strict
          - noserverino  # required to prevent data corruption


    local_volumes: {}


  inherited:
    owner: "{{ lookup('ansible.builtin.vars', 'global').owner | default('root') }}"
    group: "{{ lookup('ansible.builtin.vars', 'global').group | default('root') }}"
    mode: "{{ lookup('ansible.builtin.vars', 'global').mode | default('a=rX') }}"
    downloads: "{{ lookup('ansible.builtin.vars', 'global').working | default('/var/lib/ansible') }}/downloads"
    working: "{{ lookup('ansible.builtin.vars', 'global').working | default('/var/lib/ansible') }}/{{ role_name }}"
    install: "{{ lookup('ansible.builtin.vars', 'global').install | default('/usr/local/install') }}"
    source: "{{ lookup('ansible.builtin.vars', 'global').source | default('/usr/local/src') }}"
    secrets: "{{ lookup('ansible.builtin.vars', 'global').secrets | default('/usr/local/secrets') }}"
    kubeconfig: "{{ lookup('ansible.builtin.vars', 'global').kubeconfig | default('/etc/kubeconfig') }}"
    local_volumes: /var/lib/k8s-local-volumes
