# code: language=ansible
- name: Merge Proxmox Configuration
  ansible.builtin.set_fact:
    proxmox_vars: |
      {{ lookup('community.general.merge_variables',
                '_proxmox',
                pattern_type='suffix',
                initial_value=proxmox_defaults,
                override='ignore') }}
  tags:
    - always

- name: Configure Proxmox Repositories
  ansible.builtin.import_tasks: repos.yaml
  tags:
    - proxmox-repos

- name: Apply System Updates
  ansible.builtin.import_tasks: update.yaml
  tags:
    - proxmox-update
