- name: Set K9s Base Facts
  ansible.builtin.set_fact:
    k8s_env_path: "{{ k8s.env.path | default(k8s_defaults.env.path) }}"
    k8s_env_mode: "{{ k8s.env.mode | default(k8s_defaults.env.mode) }}"
    k8s_kubeconfig_path: "{{ k8s.kubeconfig.path | default(k8s_defaults.kubeconfig.path) }}"

- name: Set k8s Environment
  ansible.builtin.copy:
    dest: "{{ k8s_env_path }}"
    content: |
      export KUBECONFIG={{ k8s_kubeconfig_path }}
    mode: "{{ k8s_env_mode }}"

- name: Create k8s Namespaces
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
    kubeconfig: /etc/kubeconfig
  loop: "{{ k8s.namespaces | default([]) }}"
