- name: Merge k8s Variables
  ansible.builtin.set_fact:
    k8s_vars: |
      {{ lookup('community.general.merge_variables',
                '_k8s',
                initial_value=k8s_defaults,
                pattern_type='suffix') }}

- name: Set k8s Environment
  ansible.builtin.copy:
    dest: "{{ k8s_vars.global.paths.env }}"
    content: |
      export KUBECONFIG={{ k8s_vars.global.paths.kubeconfig }}
    mode: "{{ k8s_vars.global.mode }}"

- name: Configure k8s Namespaces
  ansible.builtin.include_tasks: namespaces.yaml
  tags:
    - k8s
    - namespace
    - ns

- name: Configure k8s Storage
  ansible.builtin.include_tasks: storage.yaml
  tags:
    - k8s
    - pv
    - storage

- name: Configure k8s Sealed Secrets
  ansible.builtin.include_tasks: sealed-secrets.yaml
  tags:
    - k8s
    - sealed-secrets
    - secret
    - secrets

- name: Configure k8s Secrets
  ansible.builtin.include_tasks: secrets.yaml
  tags:
    - k8s
    - pv
    - secret

- name: Configure k8s Certificate Manager and Certificates
  ansible.builtin.include_tasks: certificates.yaml
  tags:
    - cert
    - certs
    - k8s

- name: Configure k8s Metal Load Balancer
  ansible.builtin.include_tasks: metal-lb.yaml
  tags:
    - k8s
    - metal
    - metal-lb
