# code: language=ansible
- name: Sealed Secrets - Set Derived Facts
  ansible.builtin.set_fact:
    k8s_sealed_secrets_helm_values_path: "{{ k8s_vars.global.working }}/sealed-secrets--helm-values.yaml"

- name: Sealed Secrets - Create Kubernetes YAML Files Directory
  ansible.builtin.file:
    path: "{{ k8s_vars.global.working }}"
    state: directory
    mode: "{{ k8s_vars.global.mode }}"

- name: Sealed Secrets - Write Helm Values File
  ansible.builtin.copy:
    content: "{{ k8s_vars.sealed_secrets.helm_values | to_nice_yaml(indent=2) }}"
    dest: "{{ k8s_sealed_secrets_helm_values_path }}"
    mode: "{{ k8s_vars.global.mode }}"

- name: Sealed Secrets - Install/Configure Using Helm
  kubernetes.core.helm:
    name: "{{ k8s_vars.sealed_secrets.name | default('sealed-secrets') }}"
    namespace: "{{ k8s_vars.sealed_secrets.namespace | default('infrastructure') }}"
    chart_repo_url: "{{ k8s_vars.sealed_secrets.chart.url }}"
    chart_version: "{{ k8s_vars.sealed_secrets.chart.version }}"
    chart_ref: "{{ k8s_vars.sealed_secrets.chart.ref | default('sealed-secrets') }}"
    values_files: "{{ k8s_sealed_secrets_helm_values_path }}"
    create_namespace: true
    kubeconfig: "{{ k8s_vars.global.kubeconfig }}"
    wait: true
