- name: Create Kubernetes YAML Files Location
  ansible.builtin.file:
    path: /var/lib/ansible/k8s.d
    state: directory
    mode: a=rx

- name: Create Kubernetes Storage/CSI YAML Files
  ansible.builtin.template:
    src: storage-class.j2.yaml
    dest: /var/lib/ansible/k8s.d/{{ item.key }}-storage-class.yaml
  vars:
    storage_class_name: "{{ item.key }}"
    spec: "{{ item.value }}"
  loop: "{{ storage_classes | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create Kubernetes Storage/CSI Objects
  kubernetes.core.k8s:
    state: present
    apply: true
    src: /var/lib/ansible/k8s.d/{{ item.key }}-storage-class.yaml
    kubeconfig: /etc/kubeconfig
  loop: "{{ storage_classes | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

