# code: language=ansible
all_common:

  # --------------------------------------------------------------------------
  # fstab (i.e., filesystem table)
  fstab:
    smb:
      host: "{{ lookup('ansible.builtin.vars', 'lan').ip.smb }}"
      opts: username={{ lookup('ansible.builtin.vars', 'secrets_vault').smb.username }},password={{ lookup('ansible.builtin.vars', 'secrets_vault').smb.password }}
      mounts:
        homes:
          path: nas-homes
        kubernetes:
          path: nas-kubernetes


  # --------------------------------------------------------------------------
  # Name resolution/DNS
  resolve:
    domain: "{{ lookup('ansible.builtin.vars', 'lan').domain }}"
    nameservers:
      - "{{ lookup('ansible.builtin.vars', 'lan').ip.nameserver }}"
      - 8.8.8.8
      - 8.8.4.4
