# code: language=ansible
gitlab_secrets:
  backups:
    minio:
      key: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.backups.minio.key }}"
  registry:
    postgresql:
      username: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.registry.postgresql.username }}"
      password: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.registry.postgresql.password }}"
