
storage_classes:
  smb:
    provisioner: smb.csi.k8s.io
    parameters:
      source: //{{ lookup('ansible.builtin.vars', 'smb').host }}/kubernetes
      subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
      csi.storage.k8s.io/provisioner-secret-name: nas--smb
      csi.storage.k8s.io/provisioner-secret-namespace: infrastructure
      csi.storage.k8s.io/node-stage-secret-name: nas--smb
      csi.storage.k8s.io/node-stage-secret-namespace: infrastructure
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    mountOptions:
      - dir_mode=0777
      - file_mode=0777
      - uid=0
      - gid=0
      - noperm
      - mfsymlinks
      - cache=strict
      - noserverino  # required to prevent data corruption
  local:
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer

  # Added host name to the path
  smb-2025-11-01:
    provisioner: smb.csi.k8s.io
    default: "true"
    parameters:
      source: //{{ lookup('ansible.builtin.vars', 'smb').host }}/kubernetes
      subDir: "{{ inventory_hostname }}/${pvc.metadata.namespace}/${pvc.metadata.name}"
      csi.storage.k8s.io/provisioner-secret-name: nas--smb
      csi.storage.k8s.io/provisioner-secret-namespace: infrastructure
      csi.storage.k8s.io/node-stage-secret-name: nas--smb
      csi.storage.k8s.io/node-stage-secret-namespace: infrastructure
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    mountOptions:
      - dir_mode=0777
      - file_mode=0777
      - uid=0
      - gid=0
      - noperm
      - mfsymlinks
      - cache=strict
      - noserverino  # required to prevent data corruption
