k8s_certificates_secrets:
  email: "{{ lookup('ansible.builtin.vars', 'secrets_vault').email }}"
  aws:
    account: "{{ lookup('ansible.builtin.vars', 'secrets_vault').aws.account.number }}"
    name: "{{ lookup('ansible.builtin.vars', 'secrets_vault').aws.iam.name }}"
    route53:
      zoneId: "{{ lookup('ansible.builtin.vars', 'secrets_vault').aws.route53.zoneId }}"
