k8s_certificates_secrets:
  email: "{{ lookup('ansible.builtin.vars', '_secrets').email }}"
  aws:
    account: "{{ lookup('ansible.builtin.vars', '_secrets').aws.account.number }}"
    name: "{{ lookup('ansible.builtin.vars', '_secrets').aws.iam.name }}"
    route53:
      zoneId: "{{ lookup('ansible.builtin.vars', '_secrets').aws.route53.zoneId }}"
