# code: language=ansible
k8s_share:
  fetch:
    owner: kerry
    group: kerry
  share:
    owner: kerry
    group: kerry
  hosts:
    - "{{ lookup('ansible.builtin.vars', 'lan').hosts.ansible }}"
  domain: "{{ lookup('ansible.builtin.vars', 'lan').domain }}"
