# code: language=ansible
kerry_k8s_engine:
  crc:
    users:
      kerry:
        pull_secret: "{{ lookup('ansible.builtin.vars', 'secrets_vault').crc.pull_secret }}"
        config:
          preset: openshift
          disk_size: 300
        kubeconfig:
          mode: u=rw,go=r
          link: /etc/kubeconfig


kerry_common:
  packages:
    - zsh
