paths:
  kubeconfigs: /var/lib/ansible/kubeconfig.d
  facts: /var/lib/ansible/facts.d
  download: /usr/local/downloads

nfs:
  host: 192.168.0.3

smb:
  host: 192.168.0.3
  opts: username={{ lookup('ansible.builtin.vars', 'secrets').smb.username }},password={{ lookup('ansible.builtin.vars', 'secrets').smb.password }}
  mounts:
    homes:
      path: nas-homes
    kubernetes:
      path: nas-kubernetes

