paths:
  facts: /var/lib/ansible/facts.d
  download: /usr/local/downloads

dns:
  subdomain: westsidestreet.net
  nameserver: 192.168.0.3

nfs:
  host: 192.168.0.3

ansible_python_interpreter: auto_silent
