# code: language=ansible
westsidestreetnet_k8s_engine:
  k3s:
    disable:
      # K3S loadbalancer conflicts with MetalLB
      - servicelb
    registries:
      registry.westsidestreet.net:
        username: k8s-cluster
        password: "{{ lookup('ansible.builtin.vars', 'secrets_vault').k8s.glpat }}"
