
westsidestreetnet_rke2:
  registries:
    registry.westsidestreet.net:
      username: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.glpat.username }}"
      password: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.glpat.password }}"
