- name: Set C++ Development Base Facts
  ansible.builtin.set_fact:
    cpp_dev_packages: "{{ (cpp_development.packages | default([])) + (cpp_development_defaults.packages | default([])) }}"
    cpp_dev_debs: "{{ (cpp_development.debs | default([])) + (cpp_development_defaults.debs | default([])) }}"
    cpp_dev_sources: "{{ cpp_development.sources | default({}) }}"
    cpp_dev_download_path: "{{ cpp_development.paths.download | default(cpp_development_defaults.paths.download) }}"
    cpp_dev_source_path: "{{ cpp_development.paths.source | default(cpp_development_defaults.paths.source) }}"
    cpp_dev_owner: "{{ cpp_development.owner | default(cpp_development_defaults.owner) }}"
    cpp_dev_group: "{{ cpp_development.group | default(cpp_development_defaults.group) }}"
    cpp_dev_mode: "{{ cpp_development.mode | default(cpp_development_defaults.mode) }}"
    cpp_dev_tools: "{{ cpp_development.tools | default({}) | combine(cpp_development_defaults.tools) }}"
    cpp_dev_npm: "{{ (cpp_development.npm | default([])) + (cpp_development_defaults.npm | default([])) }}"

- name: Install C++ Development OS packages
  ansible.builtin.package:
    name: "{{ cpp_dev_packages }}"

- name: Install the specific .deb file
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ cpp_dev_debs }}"

- name: Create Directories for C++ Development Sources
  ansible.builtin.file:
    path: "{{ cpp_dev_download_path }}/{{ item.key }}"
    state: directory
    owner: "{{ item.value.owner | default(cpp_dev_owner) }}"
    group: "{{ item.value.group | default(cpp_dev_group) }}"
    mode: "{{ item.value.mode | default(cpp_dev_mode) }}"
  loop: "{{ cpp_dev_sources | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Download C++ Development Sources
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ cpp_dev_download_path }}/{{ item.key }}"
    mode: 0555
  register: cpp_dev_sources_downloaded
  loop: "{{ cpp_dev_sources | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Extract C++ Development Sources
  ansible.builtin.unarchive:
    src: "{{ item.dest }}"
    dest: "{{ cpp_dev_source_path }}"
    remote_src: true
    mode: 0555
  loop: "{{ cpp_dev_sources_downloaded.results }}"
  when: item.item.value.extract is defined and item.item.value.extract
  loop_control:
    label: "{{ item.item.key }}"

- name: Create Directories for C++ Development Tools
  ansible.builtin.file:
    path: "{{ cpp_dev_download_path }}/{{ item.key }}-{{ item.value.version }}"
    state: directory
    owner: "{{ item.value.owner | default(cpp_dev_owner) }}"
    group: "{{ item.value.group | default(cpp_dev_group) }}"
    mode: "{{ item.value.mode | default(cpp_dev_mode) }}"
  loop: "{{ cpp_dev_tools | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Download C++ Tools
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ cpp_dev_download_path }}/{{ item.key }}-{{ item.value.version }}"
    mode: 0555
  register: cpp_dev_tools_downloaded
  loop: "{{ cpp_dev_tools | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Extract C++ Development Tools
  ansible.builtin.unarchive:
    src: "{{ item.dest }}"
    dest: "{{ item.item.value.dest | default(cpp_dev_source_path) }}"
    remote_src: true
    mode: 0555
  loop: "{{ cpp_dev_tools_downloaded.results }}"
  when: item.item.value.extract is defined and item.item.value.extract
  loop_control:
    label: "{{ item.item.key }}"

- name: Link C++ Development Tools
  ansible.builtin.file:
    src: "{{ item.item.value.link.src }}"
    dest: "{{ item.item.value.link.dest }}"
    state: link
  loop: "{{ cpp_dev_tools_downloaded.results }}"
  when: item.item.value.link is defined
  loop_control:
    label: "{{ item.item.key }}"

- name: Install a specific Node.js package globally
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ cpp_dev_npm }}"
