# code: language=ansible
- name: NVIDIA Container Toolkit (Debian) - Download GPG Key
  ansible.builtin.get_url:
    url: "{{ nvidia_vars.container_toolkit.debian.gpg_key_url }}"
    dest: "{{ nvidia_vars.container_toolkit.debian.keyring }}.asc"
    mode: '0644'
  register: nvidia_gpg_key_download

- name: NVIDIA Container Toolkit (Debian) - Dearmor GPG Key
  ansible.builtin.command: >
    gpg --dearmor -o {{ nvidia_vars.container_toolkit.debian.keyring }}
    {{ nvidia_vars.container_toolkit.debian.keyring }}.asc
  args:
    creates: "{{ nvidia_vars.container_toolkit.debian.keyring }}"
  when: nvidia_gpg_key_download.changed

- name: NVIDIA Container Toolkit (Debian) - Add Repository
  ansible.builtin.apt_repository:
    repo: "{{ nvidia_vars.container_toolkit.debian.repo }}"
    filename: nvidia-container-toolkit
    state: present
    update_cache: true

- name: NVIDIA Container Toolkit (Debian) - Install Packages
  ansible.builtin.package:
    name: "{{ nvidia_vars.container_toolkit.packages }}"
    state: present
