# code: language=ansible
- name: NVIDIA Container Toolkit (RedHat) - Add Repository
  ansible.builtin.get_url:
    url: "{{ nvidia_vars.container_toolkit.redhat.repo.url }}"
    dest: "/etc/yum.repos.d/{{ nvidia_vars.container_toolkit.redhat.repo.name }}.repo"
    owner: root
    group: root
    mode: '0644'

- name: NVIDIA Container Toolkit (RedHat) - Install Packages
  ansible.builtin.package:
    name: "{{ nvidia_vars.container_toolkit.packages }}"
    state: present
