# code: language=ansible
- name: NVIDIA Driver (RedHat) - Enable RPM Fusion Repositories
  ansible.builtin.dnf:
    name: "{{ nvidia_vars.driver.redhat.repos }}"
    state: present
    disable_gpg_check: true

- name: NVIDIA Driver (RedHat) - Install Driver Packages
  ansible.builtin.package:
    name: "{{ nvidia_vars.driver.redhat.packages }}"
    state: present
  notify: Reboot for NVIDIA driver
