# code: language=ansible
- name: NVIDIA Driver - Enable RPM Fusion Repositories
  ansible.builtin.dnf:
    name: "{{ nvidia_vars.driver.repos }}"
    state: present
    disable_gpg_check: true

- name: NVIDIA Driver - Install Driver Packages
  ansible.builtin.package:
    name: "{{ nvidia_vars.driver.packages }}"
    state: present
  notify: Reboot for NVIDIA driver
