# code: language=ansible
- name: Merge NVIDIA Configuration
  ansible.builtin.set_fact:
    nvidia_vars: |
      {{ lookup('community.general.merge_variables',
                '_nvidia',
                pattern_type='suffix',
                initial_value=nvidia_defaults,
                override='ignore') }}

- name: Install NVIDIA GPU Drivers (Debian/Ubuntu)
  ansible.builtin.include_tasks: driver-debian.yaml
  tags:
    - driver
  when: ansible_os_family == 'Debian'

- name: Install NVIDIA GPU Drivers (RedHat/Fedora)
  ansible.builtin.include_tasks: driver-redhat.yaml
  tags:
    - driver
  when: ansible_os_family == 'RedHat'

- name: Install NVIDIA Container Toolkit (Debian/Ubuntu)
  ansible.builtin.include_tasks: container-toolkit-debian.yaml
  tags:
    - container-toolkit
  when: ansible_os_family == 'Debian'

- name: Install NVIDIA Container Toolkit (RedHat/Fedora)
  ansible.builtin.include_tasks: container-toolkit-redhat.yaml
  tags:
    - container-toolkit
  when: ansible_os_family == 'RedHat'
