# code: language=ansible
- name: Merge NVIDIA Configuration
  ansible.builtin.set_fact:
    nvidia_vars: |
      {{ lookup('community.general.merge_variables',
                '_nvidia',
                pattern_type='suffix',
                initial_value=nvidia_defaults,
                override='ignore') }}

- name: Install NVIDIA GPU Drivers
  ansible.builtin.include_tasks: driver.yaml
  tags:
    - driver

- name: Install NVIDIA Container Toolkit
  ansible.builtin.include_tasks: container-toolkit.yaml
  tags:
    - container-toolkit
