# code: language=ansible
- name: NVIDIA CTK - Read containerd config
  ansible.builtin.slurp:
    src: /etc/containerd/conf.d/99-nvidia.toml
  register: nvidia_ctk_containerd_config
  failed_when: false

- name: NVIDIA CTK - Configure containerd runtime
  ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd
  changed_when: true
  when: >-
    nvidia_ctk_containerd_config.content is not defined
    or 'runtimes.nvidia' not in
    (nvidia_ctk_containerd_config.content | b64decode)
  notify: Restart Kubernetes Runtime
