helm_applications:
  - name: nats
    value:
      namespace: dev
      url: https://nats-io.github.io/k8s/helm/charts
      ref: nats
      version: 2.12.3
      helm_values:
        config:
          merge:
            debug:   true
            trace:   true
            logtime: true
          jetstream:
            enabled: true
            fileStore:
              pvc:
                size: 10Gi
            memoryStore:
              enabled: true
              maxSize: 2Gi
