k8s_secrets:
  config:
    namespace: infrastructure
    yaml_root: /var/lib/ansible/k8s.d
  image_pull:
    - name: registry-westsidestreet.net
      namespace: dev
      auth:
        registry.westsidestreet.net:
          username: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.glpat.username }}"
          password: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.glpat.password }}"
    - name: registry-westsidestreet.net
      namespace: infrastructure
      auth:
        registry.westsidestreet.net:
          username: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.glpat.username }}"
          password: "{{ lookup('ansible.builtin.vars', '_secrets').gitlab.glpat.password }}"
