# Prerequisites:
# curl -sfL https://get.rke2.io | sudo sh -
# Reference: https://docs.rke2.io/install/quickstart
rke2_config:
  tls-san:
    - dev-vm
    - dev-vm.westsidestreet.net
    - 192.168.0.163
  registries:
    registry.westsidestreet.net:
      username: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.glpat.username }}"
      password: "{{ lookup('ansible.builtin.vars', 'secrets_vault').gitlab.glpat.password }}"
