# code: language=ansible
infrastructure01_k8s_applications:
  cnpg:
    enabled: true
    local_volumes:
      # Must match cnpg--<namespace>--<app-name>
      cnpg--devsecops-monitoring--grafana-db:
        capacity: 10Gi
        path: cnpg/devsecops/monitoring/grafana-db
        mode: u=rwx,go=
