rke2_defaults:
  installer:
    url: https://get.rke2.io
    creates: /usr/local/bin/rke2
    download: /usr/local/downloads/rke2
  kubeconfig:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /etc/kubeconfig
  kubectl:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/bin/kubectl
