# code: language=ansible
k8s_tools_defaults:

  helm:
    # renovate: datasource=github-releases depName=helm/helm
    version: v4.2.1
    url_prefix: https://get.helm.sh
    bin: /usr/local/bin/helm
    plugins:
      - https://github.com/databus23/helm-diff
      - https://github.com/helm-unittest/helm-unittest.git

  k9s:
    # renovate: datasource=github-releases depName=derailed/k9s
    version: v0.50.18
    url_prefix: https://github.com/derailed/k9s/releases/download
    bin: /usr/local/bin/k9s

  argocd:
    # renovate: datasource=github-releases depName=argoproj/argo-cd
    version: v3.4.3
    url_prefix: https://github.com/argoproj/argo-cd/releases/download
    bin: /usr/local/bin/argocd

  kubeseal:
    # renovate: datasource=github-releases depName=bitnami-labs/sealed-secrets
    version: 0.36.6
    url_prefix: https://github.com/bitnami-labs/sealed-secrets/releases/download
    bin: /usr/local/bin/kubeseal

  inherited:
    owner: "{{ lookup('ansible.builtin.vars', 'global').owner | default('root') }}"
    group: "{{ lookup('ansible.builtin.vars', 'global').group | default('root') }}"
    mode: "{{ lookup('ansible.builtin.vars', 'global').mode | default('a=rX') }}"
    downloads: "{{ lookup('ansible.builtin.vars', 'global').working | default('/var/lib/ansible') }}/downloads/{{ role_name }}"
    install: "{{ lookup('ansible.builtin.vars', 'global').install | default('/usr/local/install') }}"
    source: "{{ lookup('ansible.builtin.vars', 'global').source | default('/usr/local/src') }}"
    secrets: "{{ lookup('ansible.builtin.vars', 'global').secrets | default('/usr/local/secrets') }}"
