# code: language=ansible
- name: C++ - OS Packages
  ansible.builtin.package:
    name: "{{ devtools_vars.cpp.packages }}"

- name: C++ - Install .deb Files
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ devtools_vars.cpp.debs }}"

- name: C++ - Sources
  ansible.builtin.include_tasks: c++/sources/main.incl.yaml
  loop: "{{ devtools_vars.cpp.sources | dict2items }}"
  loop_control:
    loop_var: source
    label: "{{ source.key }}"

- name: C++ - Tools
  ansible.builtin.include_tasks: c++/tools/main.incl.yaml
  loop: "{{ devtools_vars.cpp.tools | dict2items }}"
  loop_control:
    loop_var: tool
    label: "{{ tool.key }}"
