- name: Install/Configure Default Helm Applications
  kubernetes.core.helm:
    name: "{{ item.name }}"
    namespace: "{{ item.value.namespace }}"
    chart_repo_url: "{{ item.value.url }}"
    chart_version: "{{ item.value.version }}"
    chart_ref: "{{ item.value.ref }}"
    release_values: "{{ item.value.helm_values }}"
    create_namespace: true
    kubeconfig: /etc/kubeconfig
  loop: "{{ helm_applications_defaults }}"
  loop_control:
    label: "{{ item.name }}"

- name: Install/Configure Host's Custom Helm Applications
  kubernetes.core.helm:
    name: "{{ item.name }}"
    namespace: "{{ item.value.namespace }}"
    chart_repo_url: "{{ item.value.url }}"
    chart_version: "{{ item.value.version }}"
    chart_ref: "{{ item.value.ref }}"
    release_values: "{{ item.value.helm_values }}"
    create_namespace: true
    kubeconfig: /etc/kubeconfig
  loop: "{{ helm_applications | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

