k8s_share:
  fetch:
    owner: kerry
    group: kerry
  share:
    owner: kerry
    group: kerry
  hosts:
    - wsl
  lookup:
    wsl: asusrog.westsidestreet.net
    elitedesk: elitedesk.westsidestreet.net
