# code: language=ansible
{% if rke2_config is defined and  'server' in rke2_config %}
server: "{{ rke2_config['server'] }}"
token: "{{ rke2_config['token'] }}"
{% endif %}
write-kubeconfig-mode: "0644"
{% if rke2_config is defined and 'tls-san' in rke2_config %}
tls-san:
  {% for san in rke2_config['tls-san'] %}
  - "{{ san }}"
  {% endfor %}
{% endif %}
