- name: Install packages (OS)
  ansible.builtin.package:
    name: "{{ os.packages }}"
  when: os is defined and 'packages' in os

- name: Install packages (pip)
  ansible.builtin.pip:
    name: "{{ os.pip }}"
  when: os is defined and 'pip' in os
