- name: Set OS Base Facts
  ansible.builtin.set_fact:
    os_packages: "{{ (os_host_vars.packages | default([])) + (os_group_vars.packages | default([])) + (os_defaults.packages | default([])) }}"
    os_groups: "{{ (os_host_vars.groups | default([])) + (os_group_vars.groups | default([])) + (os_defaults.groups | default([])) }}"
    os_users: "{{ (os_host_vars.users | default({})) | combine(os_group_vars.users | default({}), os_defaults.users | default({})) }}"
    os_sysctl: "{{ (os_host_vars.sysctl | default({})) | combine(os_group_vars.sysctl | default({}), os_defaults.sysctl | default({})) }}"

- name: Install OS packages
  ansible.builtin.package:
    name: "{{ os_packages }}"

- name: Ensure inotify parameters are set in sysctl.conf
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-fs-inotify.conf
    reload: yes
  loop: "{{ os_sysctl | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ os_groups | default([]) }}"

- name: Append groups to users
  ansible.builtin.user:
    name: "{{ item.key }}"
    groups: "{{ item.value.groups }}"
    append: yes
  loop: "{{ os_users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
