# code: language=ansible
- name: Merge Common Configuration
  ansible.builtin.set_fact:
    crc_vars: |
      {{ lookup('community.general.merge_variables',
                '_crc',
                pattern_type='suffix',
                initial_value=crc_defaults,
                override='ignore') }}

- name: Install CodeReady Containers Prerequisite Packages
  ansible.builtin.package:
    name: "{{ crc_vars.packages | default([]) }}"
    state: present

- name: Ensure CodeReady Containers Paths
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    mode: a=rX
  loop:
    - "{{ crc_vars.local.download }}"
    - "{{ crc_vars.local.secrets }}"

- name: Download CodeReady Containers CLI
  ansible.builtin.get_url:
    url: "{{ crc_vars.remote.url_prefix }}/{{ crc_vars.remote.version }}/{{ crc_vars.remote.filename }}"
    dest: "{{ crc_vars.local.download }}/{{ crc_vars.remote.filename }}"
    mode: a=rx

- name: Extract CodeReady Containers CLI
  ansible.builtin.unarchive:
    src: "{{ crc_vars.local.download }}/{{ crc_vars.remote.filename }}"
    dest: "{{ crc_vars.local.download }}"
    remote_src: true
    mode: a=rX

- name: Link CodeReady Containers CLI
  ansible.builtin.file:
    src: "{{ crc_vars.local.download }}/crc-linux-{{ crc_vars.remote.version }}-amd64/crc"
    path: "{{ crc_vars.local.bin }}"
    state: link

- name: Create CodeReady Containers Pull Secret File(s)
  ansible.builtin.copy:
    content: "{{ item.value.pull_secret }}"
    dest: "{{ crc_vars.local.secrets }}/{{ item.key }}--pull-secret.json"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: u=r,g=,o=
  loop: "{{ crc_vars.users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Inform User of Long-Running CRC Setup
  ansible.builtin.debug:
    msg: "Running 'crc setup' for user '{{ item.key }}'. This may take a few minutes..."
  loop: "{{ crc_vars.users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Configure CodeReady Containers for Users
  crc:
    user: "{{ item.key }}"
    crc_path: "{{ crc_vars.local.bin }}"
    config:
      consent-telemetry: "no"
      pull-secret-file: "{{ crc_vars.local.secrets }}/{{ item.key }}--pull-secret.json"
      preset: "{{ item.value.preset }}"
    setup: true
    start: true
    kubeconfig: "{{ item.value.kubeconfig }}"
  loop: "{{ crc_vars.users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  async: 600
  poll: 10
