# code: language=ansible
- name: Merge ArgoCD Variables
  ansible.builtin.set_fact:
    argocd_vars: |
      {{ lookup('community.general.merge_variables',
                '_argocd',
                initial_value=argocd_defaults,
                pattern_type='suffix',
                override='ignore') }}
  tags:
    - always

- name: Include ArgoCD Cluster Agent tasks
  ansible.builtin.include_tasks: cluster.yaml
  when: "'argocd_cluster' in group_names"
  tags:
    - argocd

- name: Include ArgoCD Server tasks
  ansible.builtin.include_tasks: server.yaml
  when: "'argocd_server' in group_names"
  tags:
    - argocd
