# code: language=ansible
- name: Merge Variables
  ansible.builtin.set_fact:
    rke2_vars: |
      {{ lookup('community.general.merge_variables',
                '_rke2',
                initial_value=rke2_defaults,
                pattern_type='suffix') }}

- name: Ensure Download Path
  ansible.builtin.file:
    name: "{{ rke2_vars.installer.download }}"
    state: directory
    mode: a=rX

- name: Download RKE2 Installer
  ansible.builtin.get_url:
    url: "{{ rke2_vars.installer.url }}"
    dest: "{{ rke2_vars.installer.download }}/installer.sh"
    mode: a=rx

- name: Run RKE2 Installer
  ansible.builtin.command: "{{ rke2_vars.installer.download }}/installer.sh"
  args:
    creates: "{{ rke2_vars.installer.creates }}"

- name: Create Rancher/RKE2 Configuration Directory
  ansible.builtin.file:
    path: "{{ rke2_vars.kubeconfig.src | dirname }}"
    state: directory
    force: true
    mode: ug=rwx,o=rx

- name: Configure Rancher/RKE2
  ansible.builtin.template:
    src: rke2-config.j2.yaml
    dest: /etc/rancher/rke2/config.yaml
    mode: ug=rwx,o=rx
  notify:
    - Restart RKE2

- name: Configure Rancher/RKE2 Registries
  ansible.builtin.template:
    src: rke2-registries.j2.yaml
    dest: /etc/rancher/rke2/registries.yaml
    mode: a=r
  vars:
    registries: "{{ rke2_vars.registries }}"
  when: "'registries' in rke2_vars"
  notify:
    - Restart RKE2

- name: Start Rancher/RKE2 Service
  ansible.builtin.service:
    name: rke2-server
    enabled: true
    state: started

- name: Flush Handlers After Updating RKE2
  ansible.builtin.meta: flush_handlers

- name: Link RKE2 kubeconfig
  ansible.builtin.file:
    src: "{{ rke2_vars.kubeconfig.src }}"
    path: "{{ rke2_vars.kubeconfig.dest }}"
    state: link

- name: Link kubectl
  ansible.builtin.file:
    src: "{{ rke2_vars.kubectl.src }}"
    path: "{{ rke2_vars.kubectl.dest }}"
    state: link
    force: true
