- name: Set RKE2 Base Facts
  ansible.builtin.set_fact:
    rke2_kubeconfig_src: "{{ rke2.kubeconfig.src | default(rke2_defaults.kubeconfig.src) }}"
    rke2_kubeconfig_dest: "{{ rke2.kubeconfig.dest | default(rke2_defaults.kubeconfig.dest) }}"
    rke2_kubectl_src: "{{ rke2.kubectl.src | default(rke2_defaults.kubectl.src) }}"
    rke2_kubectl_dest: "{{ rke2.kubectl.dest | default(rke2_defaults.kubectl.dest) }}"

- name: Create Rancher/RKE2 Configuration Directory
  ansible.builtin.file:
    path: "{{ rke2_kubeconfig_src | dirname }}"
    state: directory
    force: true
    mode: ug=rwx,o=rx

- name: Configure Rancher/RKE2
  ansible.builtin.template:
    src: rke2-config.j2.yaml
    dest: /etc/rancher/rke2/config.yaml
    mode: ug=rwx,o=rx
  notify:
    - Restart RKE2

- name: Configure Rancher/RKE2 Registries
  ansible.builtin.template:
    src: rke2-registries.j2.yaml
    dest: /etc/rancher/rke2/registries.yaml
    mode: 0440
  when: "'registries' in rke2_config"
  notify:
    - Restart RKE2

- name: Start Rancher/RKE2 Service
  ansible.builtin.service:
    name: rke2-server
    enabled: true
    state: started

- name: Flush Handlers After Updating RKE2
  ansible.builtin.meta: flush_handlers

- name: Link RKE2 kubeconfig
  ansible.builtin.file:
    src: "{{ rke2_kubeconfig_src }}"
    path: "{{ rke2_kubeconfig_dest }}"
    state: link

- name: Link kubectl
  ansible.builtin.file:
    src: "{{ rke2_kubectl_src }}"
    path: "{{ rke2_kubectl_dest }}"
    state: link
    force: true
