# code: language=ansible
- name: K3S - Ensure Download Path
  ansible.builtin.file:
    name: "{{ k8s_engine_vars.global.downloads }}"
    state: directory
    mode: a=rX

- name: K3S - Download K3S Installer
  ansible.builtin.get_url:
    url: "{{ k8s_engine_vars.k3s.installer.url }}"
    dest: "{{ k8s_engine_vars.global.downloads }}/k3s-installer.sh"
    mode: a=rx

- name: K3S - Run K3S Installer
  ansible.builtin.command: "{{ k8s_engine_vars.global.downloads }}/k3s-installer.sh"
  args:
    creates: "{{ k8s_engine_vars.k3s.installer.creates }}"

- name: K3S - Create Rancher/K3S Configuration Directory
  ansible.builtin.file:
    path: "{{ k8s_engine_vars.k3s.kubeconfig.src | dirname }}"
    state: directory
    force: true
    mode: ug=rwx,o=rx

- name: K3S - Configure Rancher/K3S
  ansible.builtin.template:
    src: k3s/config.j2.yaml
    dest: /etc/rancher/k3s/config.yaml
    mode: ug=rwx,o=rx
  notify:
    - Restart K3S

- name: K3S - Configure Rancher/K3S Registries
  ansible.builtin.template:
    src: k3s/registries.j2.yaml
    dest: /etc/rancher/k3s/registries.yaml
    mode: a=r
  vars:
    registries: "{{ k8s_engine_vars.k3s.registries }}"
  when: "'registries' in k8s_engine_vars.k3s"
  notify:
    - Restart K3S

- name: K3S - Start Rancher/K3S Service
  ansible.builtin.service:
    name: k3s
    enabled: true
    state: started

- name: K3S - Flush Handlers After Updating K3S
  ansible.builtin.meta: flush_handlers

- name: K3S - Link K3S kubeconfig
  ansible.builtin.file:
    src: "{{ k8s_engine_vars.k3s.kubeconfig.src }}"
    path: "{{ k8s_engine_vars.k3s.kubeconfig.dest }}"
    state: link

- name: K3S - Link kubectl
  ansible.builtin.file:
    src: "{{ k8s_engine_vars.k3s.kubectl.src }}"
    path: "{{ k8s_engine_vars.k3s.kubectl.dest }}"
    state: link
    force: true
