# code: language=ansible
- name: Merge K8s Engine Configuration
  ansible.builtin.set_fact:
    k8s_engine_vars: |
      {{ lookup('community.general.merge_variables',
                '_k8s_engine',
                pattern_type='suffix',
                initial_value=k8s_engine_defaults,
                override='ignore') }}

- name: Install RKE2
  ansible.builtin.import_tasks: rke2.yaml
  tags:
    - rke2
  when: k8s_engine.role == 'rke2'

- name: Install OpenShift Local
  ansible.builtin.import_tasks: crc.yaml
  tags:
    - crc
  when: k8s_engine.role == 'crc'
