# code: language=ansible
nvidia5080_k8s_applications:
  gpu:
    enabled: true

  cnpg:
    enabled: true
    local_volumes:
      cnpg--home-lab-local-inference--open-webui-db:
        capacity: 10Gi
        path: cnpg/home-lab/local-inference/open-webui-db
        mode: u=rwx,go=
