# code: language=ansible
nvidia5080_k8s:

  metallb:
    pool:
      # NOTE: Reserved these in the Netgear router by setting the upper
      #       limit of the router's IP range to a.b.c.199
      - 192.168.0.200-192.168.0.210

nvidia5080_k8s_engine:
  crc:
    # To make the GPU available to OpenShiftLocal/CRC
    # https://developers.redhat.com/articles/2025/11/27/how-enable-nvidia-gpu-acceleration-openshift-local#
    # $ sudo lspci -nnk | grep NVIDIA
    # 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GB203 [GeForce RTX 5080] [10de:2c02] (rev a1)
    #         Kernel modules: nouveau, nvidia_drm, nvidia
    # 01:00.1 Audio device [0403]: NVIDIA Corporation GB203 High Definition Audio Controller [10de:22e9] (rev a1)
	  # Subsystem: NVIDIA Corporation Device [10de:0000]
    #         Kernel modules: snd_hda_intel
    users:
      kerry:
        config:
          cpus: 24

    operators:
      # NOTE: This is here temporarily in order to migrate GitLab off of
      #       `elitedesk` so that it can be rebuilt, after which it will
      #       once again be the home of GitLab and this can be removed:
      gitlab-operator-kubernetes:
        group: cluster-operators
        source: community-operators

      # This is to allow the cluster to discover the GPU passed from the host
      node-discovery-operator:
        group: cluster-operators
        source: community-operators
