nvidia5080_vllm:
  enabled: true

  helm_values:
    image:
      command:
        - vllm
        - serve
        - /data/
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"

    resources:
      requests:
        cpu: 4
        memory: 16Gi
        nvidia.com/gpu: 1
      limits:
        cpu: 4
        memory: 16Gi
        nvidia.com/gpu: 1

    extraInit:
      pvcStorage: 50Gi
      awsEc2MetadataDisabled: true

    secrets:
      s3endpoint: "http://{{ lookup('ansible.builtin.vars', 'lan').endpoint.nas_minio }}"
      s3bucketname: machine-learning-models
      s3accesskeyid: "{{ lookup('ansible.builtin.vars', 'secrets_vault').vllm.access }}"
      s3accesskey: "{{ lookup('ansible.builtin.vars', 'secrets_vault').vllm.key }}"
