cpp_development_os_packages:
  packages:
    - clangd-20
    - clang-format-20
    - clang-tidy-20
    - cmake
    - gdb
    - gcovr
    - lcov

    # OpenGL
    - libglfw3
    - libglfw3-dev

    # Protobuf
    - libprotobuf-c-dev
    - protobuf-c-compiler

    # Pistache (CPP REST Server)
    - libpistache-dev
    # - libpistache0t64

cpp_development:
  sources:
    mujoco:
      version: 3.4.0
      url: https://github.com/google-deepmind/mujoco/releases/download/3.4.0/mujoco-3.4.0-linux-x86_64.tar.gz
      extract: true
  paths:
    download: /usr/local/downloads
