argocd:
  cli:
    version: v2.14.11
    server:
      username: admin
      password: "{{ lookup('ansible.builtin.vars', 'secrets').argocd.admin.password }}"
      port: 30443
  helm:
    ref: argo-cd
    repo:
      name: argo
      url: https://argoproj.github.io/argo-helm
      version: 7.8.2
    helm_values:
      global:
        domain: argocd.westsidestreet.net
      server:
        ingress:
          enabled: true
          tls: true
          ingressClassName: gitlab-nginx
        service:
          type: LoadBalancer
      configs:
        ssh:
          knownHosts: "{{ lookup('ansible.builtin.vars', 'secrets').ssh.knownHosts }}"
        credentialTemplates:
          kerrys-learning-lab:
            url: git@gitlab.westsidestreet.net:kerrys-learning-lab
            sshPrivateKey: |
              {{ lookup('ansible.builtin.vars', 'secrets').ssh.privateKey }}
        repositories:
          boids-argocd:
            name: boids-argocd
            url: git@gitlab.westsidestreet.net:kerrys-learning-lab/boids/boids-argocd.git
          elasticsearch-helm-chart:
            name: elasticsearch-helm-chart
            url: git@gitlab.westsidestreet.net:kerrys-learning-lab/devsecops/helm-charts/elasticsearch-helm-chart.git
          nats:
            name: nats
            url: https://nats-io.github.io/k8s/helm/charts/
            type: helm
  k8s:
    certificates:
      argocd-server:
        dnsNames:
          - argocd.westsidestreet.net
  projects:
    boids:
      description: |
        Boids is an artificial life program, developed by Craig Reynolds in
        1986, which simulates the flocking behaviour of birds, and related
        group motion.
      destination:
        name: "*"
  applicationsets:
    boids:
      source:
        url: git@gitlab.westsidestreet.net:kerrys-learning-lab/boids/boids-argocd.git
        ref: main
        path: "*"
      destination:
        name: wsl
