# code: language=ansible
k8s_applications_defaults:
  elastic_operator:
    version: 3.3.0
    url:
      prefix: https://download.elastic.co/downloads/eck
      resources:
        - crds.yaml
        - operator.yaml

  gpu:
    enabled: false
    node_feature_discovery:
      namespace: node-feature-discovery
      helm:
        name: node-feature-discovery
        chart:
          oci: oci://registry.k8s.io/nfd/charts/node-feature-discovery
          version: "0.18.3"
      helm_values: {}
    nvidia_device_plugin:
      namespace: nvidia-device-plugin
      helm:
        name: nvidia-device-plugin
        chart:
          url: https://nvidia.github.io/k8s-device-plugin
          ref: nvidia-device-plugin
          version: "0.17.1"
      helm_values:
        runtimeClassName: nvidia

  helm: {}

  inherited:
    kubeconfig: "{{ lookup('ansible.builtin.vars', 'global').kubeconfig | default('/etc/kubeconfig') }}"
