# code: language=ansible
k8s_applications_defaults:
  elastic_operator:
    version: 3.3.0
    url:
      prefix: https://download.elastic.co/downloads/eck
      resources:
        - crds.yaml
        - operator.yaml

  gpu:
    enabled: false
    node_feature_discovery:
      namespace: node-feature-discovery
      helm:
        name: node-feature-discovery
        chart:
          oci: oci://registry.k8s.io/nfd/charts/node-feature-discovery
          version: "0.18.3"
      helm_values: {}
    nvidia_device_plugin:
      namespace: nvidia-device-plugin
      helm:
        name: nvidia-device-plugin
        chart:
          url: https://nvidia.github.io/k8s-device-plugin
          ref: nvidia-device-plugin
          version: "0.17.1"
      helm_values:
        runtimeClassName: nvidia

  cnpg:
    enabled: false
    storage_class: cnpg-local
    helm:
      name: cnpg
      namespace: cnpg-system
      chart:
        url: https://cloudnative-pg.github.io/charts
        ref: cloudnative-pg
        version: "0.22.0"
    helm_values: {}
    local_volumes: {}

  helm: {}

  inherited:
    owner: "{{ lookup('ansible.builtin.vars', 'global').owner | default('root') }}"
    group: "{{ lookup('ansible.builtin.vars', 'global').group | default('root') }}"
    mode: "{{ lookup('ansible.builtin.vars', 'global').mode | default('a=rX') }}"
    local_volumes: /var/lib/k8s-local-volumes
    kubeconfig: "{{ lookup('ansible.builtin.vars', 'global').kubeconfig | default('/etc/kubeconfig') }}"
