# code: language=ansible
- name: Configure CertBot VirtualEnv
  ansible.builtin.shell:
    cmd: python3 -m venv {{ certbot.venv }}
    creates: "{{ certbot.venv }}"
  notify:
    - Upgrade CertBot Pip

- name: Install CertBot Packages
  ansible.builtin.pip:
    name: "{{ certbot.packages }}"
    virtualenv: "{{ certbot.venv }}"

- name: Link CertBot Executable
  ansible.builtin.file:
    src: "{{ certbot.venv}}/bin/certbot"
    dest: /usr/bin/certbot
    state: link

- name: Let's Encrypt Directory Permissions
  ansible.builtin.file:
    name: /etc/letsencrypt/{{ item }}
    state: directory
    mode: "0655"
  loop:
    - live
    - archive
  loop_control:
    label: "{{ item }}"
