# code: language=ansible
proxmox01_common:
  fqdn: proxmox01.westsidestreet.net

  users_and_groups:
    users:
      claude: "{{ lookup('ansible.builtin.vars', 'global').claude }}"
      hermes: "{{ lookup('ansible.builtin.vars', 'global').hermes }}"
      kerry: "{{ lookup('ansible.builtin.vars', 'global').kerry }}"
      gitlab-runner: "{{ lookup('ansible.builtin.vars', 'global').gitlab_runner }}"
