
- name: Create Local Kubernetes Volume(s) for Development
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ item.key }}"
        labels:
          owner: "{{ item.key }}"
      spec:
        capacity:
          storage: "{{ item.value.capacity | default('10Gi') }}"
        accessModes:
          - "{{ item.value.accessMode | default('ReadWriteOnce') }}"
        persistentVolumeReclaimPolicy: "{{ item.value.reclaimPolicy | default('Retain') }}"
        storageClassName: local
        hostPath:
          path: "{{ item.value.path }}"
    kubeconfig: /etc/kubeconfig
  loop: "{{ dev.k8s.volumes.local | default({}) |dict2items }}"
  loop_control:
    label: "{{ item.key }}"
