# code: language=ansible
- name: Chezmoi - Ensure config directory
  ansible.builtin.file:
    path: /home/{{ user.key }}/.config/chezmoi
    state: directory
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    mode: u=rwx,go-rwx

- name: Chezmoi - Control Chezmoi Age Configuration
  ansible.builtin.template:
    src: chezmoi/age-key.txt.j2
    dest: /home/{{ user.key }}/.config/chezmoi/age-key.txt
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    mode: u=r,go-rwx
  when: "'age' in user.value.chezmoi"

- name: Chezmoi - Control Chezmoi TOML
  ansible.builtin.template:
    src: chezmoi/chezmoi.toml.j2
    dest: /home/{{ user.key }}/.config/chezmoi/chezmoi.toml
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    mode: u=r,go-rwx
