# code: language=ansible
- name: Users and Groups - Create User - {{ user.key }}
  ansible.builtin.user:
    name: "{{ user.key }}"
    shell: "{{ user.value.shell | default('/bin/bash') }}"
    create_home: true
    state: present
  when: user.value.create | default(false)

- name: Users and Groups - Append Groups to User - {{ user.key }}
  ansible.builtin.user:
    name: "{{ user.key }}"
    groups: "{{ user.value.groups }}"
    append: true
  when: "'groups' in user.value and user.value.groups | length > 0"

- name: Users and Groups - Generate SSH Keys - {{ user.key }}
  ansible.builtin.user:
    name: "{{ user.key }}"
    generate_ssh_key: true
    ssh_key_type: "{{ user.value.ssh_key.type | default('ed25519') }}"
    ssh_key_comment: "{{ user.value.ssh_key.comment | default(user.key + '@' + ansible_hostname) }}"
    ssh_key_file: ".ssh/id_{{ user.value.ssh_key.type | default('ed25519') }}"
  when: >-
    user.value.ssh_key is defined
    and user.value.ssh_key.generate | default(false)
    and user.value.ssh_key.private is not defined
  register: ssh_key_result

- name: Users and Groups - Ensure SSH Directory - {{ user.key }}
  ansible.builtin.file:
    path: "~{{ user.key }}/.ssh"
    state: directory
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    mode: '0700'
  when: user.value.ssh_key is defined and user.value.ssh_key.private is defined

- name: Users and Groups - Write SSH Private Keys - {{ user.key }}
  ansible.builtin.copy:
    content: "{{ user.value.ssh_key.private }}"
    dest: "~{{ user.key }}/.ssh/id_{{ user.value.ssh_key.type | default('ed25519') }}"
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    mode: '0600'
  when: user.value.ssh_key is defined and user.value.ssh_key.private is defined
  no_log: true

- name: Users and Groups - Write SSH Public Keys - {{ user.key }}
  ansible.builtin.copy:
    content: "{{ user.value.ssh_key.public }}"
    dest: "~{{ user.key }}/.ssh/id_{{ user.value.ssh_key.type | default('ed25519') }}.pub"
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    mode: '0644'
  when: user.value.ssh_key is defined and user.value.ssh_key.public is defined

- name: Users and Groups - Set Environment Variables - {{ user.key }}
  ansible.builtin.include_tasks: ../user-env-vars.yaml
  when: user.value.env is defined
  vars:
    user_name: "{{ user.key }}"
    user_env: "{{ user.value.env }}"

- name: Configure Chezmoi - {{ user.key }}
  ansible.builtin.include_tasks: chezmoi.yaml
  when: "'chezmoi' in user.value"
  tags:
    - chezmoi
