# code: language=ansible
- name: ArgoCD CLI - Set Derived Facts (1 of 2)
  ansible.builtin.set_fact:
    k8s_tools_argocd_filename: "argocd-{{ ansible_system | lower }}-{{ ansible_local['arch']['dpkg'] }}"
    k8s_tools_argocd_download_path: "{{ k8s_tools_vars.inherited.downloads }}/argocd/{{ k8s_tools_vars.argocd.version }}"
    k8s_tools_argocd_install_path: "{{ k8s_tools_vars.inherited.install }}/argocd-{{ k8s_tools_vars.argocd.version }}"

- name: ArgoCD CLI - Set Derived Facts (2 of 2)
  ansible.builtin.set_fact:
    k8s_tools_argocd_url: "{{ k8s_tools_vars.argocd.url_prefix }}/{{ k8s_tools_vars.argocd.version }}/{{ k8s_tools_argocd_filename }}"

- name: ArgoCD CLI - Ensure Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ k8s_tools_vars.inherited.owner }}"
    group: "{{ k8s_tools_vars.inherited.group }}"
    mode: "{{ k8s_tools_vars.inherited.mode }}"
  loop:
    - "{{ k8s_tools_argocd_download_path }}"
    - "{{ k8s_tools_argocd_install_path }}"

- name: ArgoCD CLI - Download
  ansible.builtin.get_url:
    url: "{{ k8s_tools_argocd_url }}"
    dest: "{{ k8s_tools_argocd_download_path }}/{{ k8s_tools_argocd_filename }}"
    mode: "{{ k8s_tools_vars.inherited.mode }}"

- name: ArgoCD CLI - Install
  ansible.builtin.copy:
    src: "{{ k8s_tools_argocd_download_path }}/{{ k8s_tools_argocd_filename }}"
    dest: "{{ k8s_tools_argocd_install_path }}/{{ k8s_tools_argocd_filename }}"
    remote_src: true
    mode: a=rx

- name: ArgoCD CLI - Link Binary
  ansible.builtin.file:
    src: "{{ k8s_tools_argocd_install_path }}/{{ k8s_tools_argocd_filename }}"
    dest: "{{ k8s_tools_vars.argocd.bin }}"
    state: link
