# code: language=ansible
- name: Set Helm Derived Facts (1 of 2)
  ansible.builtin.set_fact:
    k8s_tools_helm_filename: "helm-{{ k8s_tools_vars.helm.version }}-{{ ansible_system | lower }}-{{ ansible_local['arch']['container'] }}.tar.gz"
    k8s_tools_helm_download_path: "{{ k8s_tools_vars.inherited.downloads }}/helm/{{ k8s_tools_vars.helm.version }}"
    k8s_tools_helm_install_path: "{{ k8s_tools_vars.inherited.install }}/helm-{{ k8s_tools_vars.helm.version }}"

- name: Set Helm Derived Facts (2 of 2)
  ansible.builtin.set_fact:
    k8s_tools_helm_url: "{{ k8s_tools_vars.helm.url_prefix }}/{{ k8s_tools_helm_filename }}"

- name: Ensure Helm install directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ k8s_tools_vars.inherited.owner }}"
    group: "{{ k8s_tools_vars.inherited.group }}"
    mode: "{{ k8s_tools_vars.inherited.mode }}"
  loop:
    - "{{ k8s_tools_helm_download_path }}"
    - "{{ k8s_tools_helm_install_path }}"

- name: Download Helm
  ansible.builtin.get_url:
    url: "{{ k8s_tools_helm_url }}"
    dest: "{{ k8s_tools_helm_download_path }}/{{ k8s_tools_helm_filename }}"
    mode: "0644"

- name: Extract Helm
  ansible.builtin.unarchive:
    src: "{{ k8s_tools_helm_download_path }}/{{ k8s_tools_helm_filename }}"
    dest: "{{ k8s_tools_helm_install_path }}"
    remote_src: true
    creates: "{{ k8s_tools_helm_install_path }}/{{ ansible_system | lower }}-{{ ansible_local['arch']['container'] }}/helm"

- name: Link Helm binary
  ansible.builtin.file:
    src: "{{ k8s_tools_helm_install_path }}/{{ ansible_system | lower }}-{{ ansible_local['arch']['container'] }}/helm"
    dest: "{{ k8s_tools_vars.helm.bin }}"
    state: link

- name: Install Helm Plugins
  kubernetes.core.helm_plugin:
    plugin_path: "{{ item }}"
    state: present
    verify: false
  loop: "{{ k8s_tools_vars.helm.plugins | default([]) }}"
