# code: language=ansible
- name: Set Kubeseal Derived Facts (1 of 2)
  ansible.builtin.set_fact:
    k8s_tools_kubeseal_filename: "kubeseal-{{ k8s_tools_vars.kubeseal.version }}-{{ ansible_system | lower }}-{{ ansible_local['arch']['dpkg'] }}.tar.gz"
    k8s_tools_kubeseal_download_path: "{{ k8s_tools_vars.inherited.downloads }}/kubeseal/{{ k8s_tools_vars.kubeseal.version }}"
    k8s_tools_kubeseal_install_path: "{{ k8s_tools_vars.inherited.install }}/kubeseal-{{ k8s_tools_vars.kubeseal.version }}"

- name: Set Kubeseal Derived Facts (2 of 2)
  ansible.builtin.set_fact:
    k8s_tools_kubeseal_url: "{{ k8s_tools_vars.kubeseal.url_prefix }}/v{{ k8s_tools_vars.kubeseal.version }}/{{ k8s_tools_kubeseal_filename }}"

- name: Ensure Kubeseal install directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ k8s_tools_vars.inherited.owner }}"
    group: "{{ k8s_tools_vars.inherited.group }}"
    mode: "{{ k8s_tools_vars.inherited.mode }}"
  loop:
    - "{{ k8s_tools_kubeseal_download_path }}"
    - "{{ k8s_tools_kubeseal_install_path }}"

- name: Download Kubeseal
  ansible.builtin.get_url:
    url: "{{ k8s_tools_kubeseal_url }}"
    dest: "{{ k8s_tools_kubeseal_download_path }}/{{ k8s_tools_kubeseal_filename }}"
    mode: "0644"

- name: Extract Kubeseal
  ansible.builtin.unarchive:
    src: "{{ k8s_tools_kubeseal_download_path }}/{{ k8s_tools_kubeseal_filename }}"
    dest: "{{ k8s_tools_kubeseal_install_path }}"
    remote_src: true
    creates: "{{ k8s_tools_kubeseal_install_path }}/kubeseal"

- name: Link Kubeseal binary
  ansible.builtin.file:
    src: "{{ k8s_tools_kubeseal_install_path }}/kubeseal"
    dest: "{{ k8s_tools_vars.kubeseal.bin }}"
    state: link
