#jinja2: lstrip_blocks: True
# code: language=ansible
{% if 'server' in k8s_engine_vars.k3s %}
server: "{{ k8s_engine_vars.k3s['server'] }}"
token: "{{ k8s_engine_vars.k3s['token'] }}"
{% endif %}
write-kubeconfig-mode: "0644"
advertise-address: "{{ k8s_engine_vars.k3s.address | default(ansible_default_ipv4.address) }}"
{% if 'tls-san' in k8s_engine_vars.k3s %}
tls-san:
  {% for san in k8s_engine_vars.k3s['tls-san'] %}
  - "{{ san }}"
  {% endfor %}
{% endif %}
{% if 'disable' in k8s_engine_vars.k3s %}
disable:
  {% for disable in k8s_engine_vars.k3s.disable %}
  - "{{ disable }}"
  {% endfor %}
{% endif %}
