# code: language=ansible
- name: Merge Ansible Configuration
  ansible.builtin.set_fact:
    ansible_vars: |
      {{ lookup('community.general.merge_variables',
                '_ansible',
                pattern_type='suffix',
                initial_value=ansible_defaults,
                override='ignore') }}

- name: Install Ansible Packages
  ansible.builtin.package:
    name: "{{ ansible_vars.packages }}"
    state: present
