- name: Set MetalLB Base Facts
  ansible.builtin.set_fact:
    metal_lb_pool: "{{ metal_lb.pool | default(false) }}"

- name: Create the IP Address Pool for Metal LB
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: metal-lb-address-pool
        namespace: infrastructure
      spec:
        addresses:
          - "{{ metal_lb.pool }}"
        autoAssign: true
    kubeconfig: /etc/kubeconfig
  when: metal_lb_pool

- name: Create the L2 Advertisement Metal LB
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: metal-lb-l2-advertisement
        namespace: infrastructure
      spec:
        ipAddressPools:
          - metal-lb-address-pool
    kubeconfig: /etc/kubeconfig
  when: metal_lb_pool
