# code: language=ansible
- name: Elasticsearch Operator - Install Resources
  kubernetes.core.k8s:
    state: present
    apply: true
    src: "{{ k8s_applications_vars.elastic_operator.url.prefix }}/{{ k8s_applications_vars.elastic_operator.version }}/{{ item }}"
    kubeconfig: "{{ k8s_applications_vars.inherited.kubeconfig }}"
  loop: "{{ k8s_applications_vars.elastic_operator.url.resources }}"
