# code: language=ansible
- name: Merge K8S Applications Variables
  ansible.builtin.set_fact:
    k8s_applications_vars: |
      {{ lookup('community.general.merge_variables',
                '_k8s_applications',
                initial_value=k8s_applications_defaults,
                pattern_type='suffix',
                override='ignore') }}

- name: Install Elasticsearch Operator
  ansible.builtin.import_tasks: elastic-operator.yaml
  when: k8s_applications_vars.elastic_operator.enabled | default(false)
  tags:
    - elasticsearch

- name: Install GPU Support
  ansible.builtin.import_tasks: gpu.yaml
  when: k8s_applications_vars.gpu.enabled | default(false)
  tags:
    - gpu

- name: Install CNPG Operator
  ansible.builtin.import_tasks: cnpg.yaml
  when: k8s_applications_vars.cnpg.enabled | default(false)
  tags:
    - cnpg

- name: Deploy vLLM Inference Server
  ansible.builtin.import_tasks: vllm.yaml
  when: k8s_applications_vars.vllm.enabled | default(false)
  tags:
    - vllm
    - inference

- name: Install/Configure Applications Using Helm
  kubernetes.core.helm:
    name: "{{ item.key }}"
    namespace: "{{ item.value.namespace }}"
    chart_repo_url: "{{ item.value.chart.url }}"
    chart_version: "{{ item.value.chart.version }}"
    chart_ref: "{{ item.value.chart.ref }}"
    release_values: "{{ item.value.helm_values }}"
    create_namespace: true
    kubeconfig: "{{ k8s_applications_vars.inherited.kubeconfig }}"
    wait: true
  loop: "{{ k8s_applications_vars.helm | dict2items }}"
  loop_control:
    label: "{{ item.key }}-{{ item.value.chart.version }}"
  when: "'url' in item.value.chart"

- name: Install/Configure Applications Using Helm OCI
  kubernetes.core.helm:
    name: "{{ item.key }}"
    namespace: "{{ item.value.namespace }}"
    chart_version: "{{ item.value.chart.version }}"
    chart_ref: "{{ item.value.chart.oci }}"
    release_values: "{{ item.value.helm_values }}"
    create_namespace: true
    kubeconfig: "{{ k8s_applications_vars.inherited.kubeconfig }}"
    wait: true
  loop: "{{ k8s_applications_vars.helm | dict2items }}"
  loop_control:
    label: "{{ item.key }}-{{ item.value.chart.version }}"
  when: "'oci' in item.value.chart"
