os_defaults:
  users: []
  groups: []
  packages:
    - bat
    - gnupg2
    - speedtest-cli
    - vim
  sysctl:
    fs.inotify.max_user_watches: 524288
    fs.inotify.max_user_instances: 524288
    fs.inotify.max_queued_events: 524288
