# code: language=ansible
monitoring_k8s_applications:
  cnpg:
    enabled: true
    local_volumes:
      cnpg--monitoring--grafana-db:
        capacity: 10Gi
        path: cnpg/monitoring/grafana-db
        mode: u=rwx,go=
