sealed_secrets_defaults:
  cli:
    version: 0.32.2
    url_prefix: https://github.com/bitnami-labs/sealed-secrets/releases/download
    paths:
      download: /var/lib/ansible
      bin: /usr/local/bin/kubeseal
    owner: root
    group: root
    mode: a=rx
