apiVersion: v1
kind: Secret
metadata:
  name: {{ item.key }}
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ item.key }}
  server: https://{{ item.key }}:6443
  config: |
    {
      "tlsClientConfig": {
        "caData": "{{ item.value.ca }}",
        "certData": "{{ item.value.client.certificate }}",
        "keyData": "{{ item.value.client.key }}",
        "serverName": "{{ item.value.server }}",
        "insecure": false
      }
    }
