# code: language=ansible
- name: Create Custom Facts Directory
  ansible.builtin.file:
    name: "{{ common_vars.global.facts }}"
    state: directory
    mode: "{{ common_vars.global.mode }}"

- name: Create Architecture Mapping Facts Script
  ansible.builtin.copy:
    src: files/arch.fact
    dest: "{{ common_vars.global.facts }}/arch.fact"
    mode: "0555"
