# code: language=ansible
- name: Filesystem Table - Create Network Mount Locations (SMB)
  ansible.builtin.file:
    state: directory
    path: /mnt/{{ item.value.path }}
    mode: a=rX
  loop: "{{ common_vars.fstab.smb.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Filesystem Table - Mount Network Shares (SMB)
  ansible.posix.mount:
    state: mounted
    src: "//{{ common_vars.fstab.smb.host }}/{{ item.key }}"
    path: /mnt/{{ item.value.path }}
    fstype: "{{ item.value.type | default('cifs') }}"
    opts: "{{ item.value.opts | default(common_vars.fstab.smb.opts) }}"
  loop: "{{ common_vars.fstab.smb.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Filesystem Table - Mount Network Home Directories (SMB)
  ansible.posix.mount:
    state: mounted
    src: "//{{ common_vars.fstab.smb.host }}/{{ common_vars.fstab.smb.homes.source }}"
    path: "{{ common_vars.fstab.smb.homes.path }}/{{ item.key }}"
    fstype: "{{ common_vars.fstab.smb.homes.type | default('cifs') }}"
    opts: "uid={{ item.value.uid }},gid={{ item.value.gid }},{{ item.value.opts | default(common_vars.fstab.smb.opts) }}"
  loop: "{{ common_vars.fstab.smb.homes.users | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: common_vars.fstab.smb.homes is defined

- name: Filesystem Table - Create Host-specific Mount Locations
  ansible.builtin.file:
    state: directory
    path: /mnt/{{ item.value.mount_path | default(item.key) }}
    owner: "{{ item.value.owner | default(root) }}"
    group: "{{ item.value.group | default(root) }}"
    mode: "{{ item.value.mode | default(755) }}"
  loop: "{{ host.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Filesystem Table - Mount Host-specific Shares/Drives (fstab)
  ansible.posix.mount:
    state: mounted
    src: "{{ item.value.src }}"
    path: /mnt/{{ item.value.mount_path | default(item.key) }}
    fstype: "{{ item.value.type }}"
  loop: "{{ host.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
