# code: language=ansible
- name: Merge Common Configuration
  ansible.builtin.set_fact:
    common_vars: |
      {{ lookup('community.general.merge_variables',
                '_common',
                pattern_type='suffix',
                initial_value=common_defaults,
                override='ignore') }}
  tags:
    - always

- name: Install/Configure OS Packages
  ansible.builtin.import_tasks: packages.yaml
  tags:
    - os
    - packages

- name: Install/Configure OS Settings
  ansible.builtin.import_tasks: settings.yaml
  tags:
    - os
    - settings

- name: Configure Users and Groups
  ansible.builtin.import_tasks: users-and-groups.yaml
  tags:
    - users
    - groups

- name: Configure Name Resolution
  ansible.builtin.import_tasks: resolve.yaml
  tags:
    - dns
    - resolve

- name: Disk Management (partitions, LVM, filesystems)
  ansible.builtin.import_tasks: disk-management.yaml
  tags:
    - disk
    - lvm
    - filesystem

- name: Filesystem Table (fstab)
  ansible.builtin.import_tasks: fstab.yaml
  tags:
    - filesystem
    - fstab
    - nfs
    - smb

- name: Create Custom Ansible Facts
  ansible.builtin.import_tasks: facts.yaml

- name: Ensure Common Paths
  ansible.builtin.file:
    name: "{{ item.value }}"
    state: directory
    mode: '0655'
  loop: "{{ common_vars.paths | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Ensure Host-specific Paths
  ansible.builtin.file:
    name: "{{ item.value }}"
    state: directory
    mode: '0755'
  loop: "{{ host.paths | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
