- name: Install host-specific packages (OS)
  ansible.builtin.package:
    name: "{{ host.packages }}"
  when: host is defined and 'packages' in host

- name: Create Network Mount Locations (SMB)
  ansible.builtin.file:
    state: directory
    path: /mnt/{{ item.value.path }}
  loop: "{{ smb.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Mount Network Shares (SMB)
  ansible.posix.mount:
    state: mounted
    src: "//{{ smb.host }}/{{ item.key }}"
    path: /mnt/{{ item.value.path }}
    fstype: "{{ item.value.type | default('cifs') }}"
    opts: "{{ item.value.opts | default(smb.opts) }}"
  loop: "{{ smb.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Mount Network Home Directories (SMB)
  ansible.posix.mount:
    state: mounted
    src: "//{{ smb.host }}/{{ smb.homes.source }}"
    path: "{{ smb.homes.path }}/{{ item.key }}"
    fstype: "{{ smb.homes.type | default('cifs') }}"
    opts: "uid={{ item.value.uid }},gid={{ item.value.gid }},{{ item.value.opts | default(smb.opts) }}"
  loop: "{{ smb.homes.users | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: smb.homes is defined

- name: Create Host-specific Mount Locations
  ansible.builtin.file:
    state: directory
    path: /mnt/{{ item.value.mount_path | default(item.key) }}
  loop: "{{ host.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Mount Host-specific Shares/Drives (fstab)
  ansible.posix.mount:
    state: mounted
    src: "{{ item.value.src }}"
    path: /mnt/{{ item.value.mount_path | default(item.key) }}
    fstype: "{{ item.value.type }}"
  loop: "{{ host.mounts | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create Custom Ansible Facts
  import_tasks: facts.yaml

- name: Ensure Common Paths
  ansible.builtin.file:
    name: "{{ item.value }}"
    state: directory
    mode: '0655'
  loop: "{{ paths | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Ensure Host-specific Paths
  ansible.builtin.file:
    name: "{{ item.value }}"
    state: directory
    mode: '0755'
  loop: "{{ host.paths | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
