# code: language=ansible
- name: Update Apt, if applicable
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  when: "'ubuntu' in group_names"


- name: OS Packages - Install Packages
  ansible.builtin.package:
    name: "{{ common_vars.packages }}"
