# code: language=ansible
- name: "Configure /etc/profile.d/{{ item.key }}.sh"
  ansible.builtin.template:
    src: profile-d.j2
    dest: "/etc/profile.d/{{ item.key }}.sh"
    owner: "{{ common_vars.inherited.owner }}"
    group: "{{ common_vars.inherited.group }}"
    mode: "{{ common_vars.inherited.mode }}"
  vars:
    env_vars: "{{ item.value }}"
  loop: "{{ common_vars.profile_d | dict2items }}"
  loop_control:
    label: "{{ item.key }}.sh"
