# code: language=ansible
- name: Resolve - Set Manual Hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.key }}.*$"
    line: "{{ item.key }} {{ item.value | join(' ') }}"
    state: present
  loop: "{{ common_vars.resolve.hosts | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Set Resolve Derived Facts
  ansible.builtin.set_fact:
    common_common_common_resolve_any_nameserver_needs_update: "{{ common_vars.resolve.nameservers | join(' ') }}"
    common_resolve_any_nameserver_needs_update: false

- name: Resolve - Retrieve Existing Nameservers
  ansible.builtin.command: "{{ common_vars.resolve.resolvectl }} dns {{ common_vars.resolve.link }}"
  register: common_resolve_dns_existing_output
  changed_when: false
  when: "'link' in common_vars.resolve"

- name: Resolve - Check Nameservers
  ansible.builtin.set_fact:
    common_resolve_any_nameserver_needs_update: "{{ common_resolve_any_nameserver_needs_update or item not in common_resolve_dns_existing_output.stdout }}"
  loop: "{{ common_vars.resolve.nameservers }}"
  when: "'link' in common_vars.resolve"

- name: Resolve - Update Nameservers
  ansible.builtin.command: |
    {{ common_vars.resolve.resolvectl }} dns  {{ common_vars.resolve.link }}
                                              {{ common_common_common_resolve_any_nameserver_needs_update }}
  register: common_resolve_dns_existing_output
  when: "'link' in common_vars.resolve and common_resolve_any_nameserver_needs_update"
  changed_when: "'link' in common_vars.resolve and common_resolve_any_nameserver_needs_update"

- name: Resolve - Retrieve Existing Search Domain
  ansible.builtin.command: "{{ common_vars.resolve.resolvectl }} domain {{ common_vars.resolve.link }}"
  register: common_resolve_domain_existing_output
  changed_when: false
  when: "'link' in common_vars.resolve"

- name: Resolve - Update Search Domain
  ansible.builtin.command: "{{ common_vars.resolve.resolvectl }} domain {{ common_vars.resolve.link }} {{ common_vars.resolve.domain }}"
  register: common_resolve_domain_existing_output
  when: "'link' in common_vars.resolve and common_vars.resolve.domain not in common_resolve_domain_existing_output.stdout"
  changed_when: "'link' in common_vars.resolve and common_vars.resolve.domain not in common_resolve_domain_existing_output.stdout"
