# code: language=ansible
- name: Users and Groups - Create Groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ common_vars.users_and_groups.groups | default([]) }}"

- name: Configure Users
  ansible.builtin.include_tasks: user/main.yaml
  loop: "{{ common_vars.users_and_groups.users | dict2items }}"
  loop_control:
    label: "{{ user.key }}"
    loop_var: user
