# code: language=ansible
- name: "Set environment variable {{ item.key }} for {{ user_name }}"
  ansible.builtin.lineinfile:
    path: "~{{ user_name }}/.bashrc"
    line: "export {{ item.key }}={{ item.value }}"
    regexp: "^export {{ item.key }}="
    state: present
  loop: "{{ user_env | dict2items }}"
  loop_control:
    label: "{{ user_name }} - {{ item.key }}"
