- name: Set K8s Secrets Base Facts
  ansible.builtin.set_fact:
    k8s_secrets_yaml_root: "{{ k8s_secrets.config.yaml_root | default(k8s_secrets_defaults.yaml_root) }}"
    k8s_secrets_namespace: "{{ k8s_secrets.config.namespace | default(k8s_secrets_defaults.namespace) }}"
    k8s_secrets_owner: "{{ k8s_secrets.config.owner | default(k8s_secrets_defaults.owner) }}"
    k8s_secrets_group: "{{ k8s_secrets.config.group | default(k8s_secrets_defaults.group) }}"
    k8s_secrets_mode: "{{ k8s_secrets.config.mode | default(k8s_secrets_defaults.mode) }}"

- name: Create Parent Directory for Kubernetes StringData Secrets
  ansible.builtin.file:
    path: "{{ k8s_secrets_yaml_root }}"
    state: directory
    mode: a=rx

- name: Create Kubernetes StringData Secrets
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: "{{ item.value.type | default('Opaque') }}"
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default(k8s_secrets_namespace) | lower }}"
      stringData: "{{ item.value.stringData }}"
    kubeconfig: /etc/kubeconfig
  when: "'stringData' in item.value"
  loop: "{{ k8s_secrets.string | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.value.namespace | default(k8s_secrets_namespace) | lower }}.{{ item.key }}"
