extra:
  packages:
    # NOTE: Prior to installing this package, must perform
    #       - sudo wget -O /etc/apt/sources.list.d/gitlab-ci-local.sources https://gitlab-ci-local-ppa.firecow.dk/gitlab-ci-local.sources
    #       - sudo apt update
    #       as described here: https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#installation
    - gitlab-ci-local
