# code: language=ansible

- name: Create Local Kubernetes Volume Directories
  ansible.builtin.file:
    path: "{{ item.key }}"
    state: directory
    owner: "{{ item.value.owner | default('root') }}"
    group: "{{ item.value.group | default('root') }}"
    mode: "{{ item.value.mode }}"
  loop: "{{ mlflow.directories | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create Local Kubernetes Volume(s) for MLFlow
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ item.key }}"
        labels:
          owner: "{{ item.key }}"
      spec:
        capacity:
          storage: "{{ item.value.capacity | default('10Gi') }}"
        accessModes:
          - "{{ item.value.accessMode | default('ReadWriteOnce') }}"
        persistentVolumeReclaimPolicy: "{{ item.value.reclaimPolicy | default('Retain') }}"
        storageClassName: local
        hostPath:
          path: "{{ item.value.path }}"
    kubeconfig: /etc/kubeconfig
  loop: "{{ mlflow.k8s.volumes.local | default({}) |dict2items }}"
  loop_control:
    label: "{{ item.key }}"
