vllm_defaults:
  enabled: false

  # renovate: datasource=github-releases depName=vllm-project/vllm
  version: 0.16.0
  helm:
    name: vllm
    namespace: vllm
    chart:
      url: https://github.com/vllm-project/vllm/releases/download
      path: examples/online_serving/chart-helm

  helm_values: {}

  inherited:
    mode: "{{ lookup('ansible.builtin.vars', 'global').mode | default('a=rX') }}"
    downloads: "{{ lookup('ansible.builtin.vars', 'global').working | default('/var/lib/ansible') }}/downloads/{{ role_name }}"
    install: "{{ lookup('ansible.builtin.vars', 'global').install | default('/usr/local/install') }}"
    kubeconfig: "{{ lookup('ansible.builtin.vars', 'global').kubeconfig | default('/etc/kubeconfig') }}"
