- name: Set K8s Local Volumes Base Facts
  ansible.builtin.set_fact:
    k8s_local_volumes_root_dir: "{{ k8s_local_volumes.config.root_dir | default(k8s_local_volumes_defaults.root_dir) }}"
    k8s_local_volumes_owner: "{{ k8s_local_volumes.config.owner | default(k8s_local_volumes_defaults.owner) }}"
    k8s_local_volumes_group: "{{ k8s_local_volumes.config.group | default(k8s_local_volumes_defaults.group) }}"
    k8s_local_volumes_mode: "{{ k8s_local_volumes.config.mode | default(k8s_local_volumes_defaults.mode) }}"

- name: Create K8s Local Storage Class
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
      provisioner: kubernetes.io/no-provisioner
      reclaimPolicy: Retain
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: false
    kubeconfig: /etc/kubeconfig


- name: Create Local Kubernetes Volume Root Directories
  ansible.builtin.file:
    path: "{{ k8s_local_volumes_root_dir }}"
    state: directory
    owner: "{{ k8s_local_volumes_owner }}"
    group: "{{ k8s_local_volumes_group }}"
    mode: "{{ k8s_local_volumes_mode }}"

# We create the parent directories with less restrictive access
- name: Create Local Kubernetes Volume Directory Parents
  ansible.builtin.file:
    path: "{{ k8s_local_volumes_root_dir }}/{{ item.value.path | dirname }}"
    state: directory
    owner: "{{ item.value.owner | default(k8s_local_volumes_owner) }}"
    group: "{{ item.value.group | default(k8s_local_volumes_group) }}"
    mode: "a=rx"
  loop: "{{ k8s_local_volumes | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: "item.key != 'config'"

- name: Create Local Kubernetes Volume Directories
  ansible.builtin.file:
    path: "{{ k8s_local_volumes_root_dir }}/{{ item.value.path }}"
    state: directory
    owner: "{{ item.value.owner | default(k8s_local_volumes_owner) }}"
    group: "{{ item.value.group | default(k8s_local_volumes_group) }}"
    mode: "{{ item.value.mode | default(k8s_local_volumes_mode) }}"
  loop: "{{ k8s_local_volumes | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: "item.key != 'config'"

- name: Create Local Kubernetes Volume(s)
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ item.key }}"
        labels:
          owner: "{{ item.key }}"
      spec:
        capacity:
          storage: "{{ item.value.capacity | default('10Gi') }}"
        accessModes:
          - "{{ item.value.accessMode | default('ReadWriteOnce') }}"
        persistentVolumeReclaimPolicy: "{{ item.value.reclaimPolicy | default('Retain') }}"
        storageClassName: local
        hostPath:
          path: "{{ k8s_local_volumes_root_dir }}/{{ item.value.path }}"
    kubeconfig: /etc/kubeconfig
  loop: "{{ k8s_local_volumes | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: "item.key != 'config'"
