dev:
  directories:
    /var/lib/k8s-local-pv:
      mode: u=rwx,go=rx
    /var/lib/k8s-local-pv/dev:
      mode: u=rwx,go=rx
    /var/lib/k8s-local-pv/dev/roadmap-dashboard:
      mode: u=rwx,go=rx
    /var/lib/k8s-local-pv/dev/roadmap-dashboard/mysql:
      owner: 27
      group: 27
      mode: u=rwx,go=rx
  k8s:
    volumes:
      local:
        roadmap-dashboard-mysql-dev:
          capacity: 20Gi
          path: /var/lib/k8s-local-pv/dev/roadmap-dashboard/mysql
    certificates:
      roadmap-dashboard-dev:
        dnsNames:
          - roadmap-dashboard-dev.westsidestreet.net
