# code: language=ansible
- name: Set Dependabot Base Facts
  ansible.builtin.set_fact:
    dependabot_gitlab_chart_ref: "{{ dependabot_gitlab.chart.ref | default(dependabot_gitlab_defaults.chart.ref) }}"
    dependabot_gitlab_chart_url: "{{ dependabot_gitlab.chart.url | default(dependabot_gitlab_defaults.chart.url) }}"
    dependabot_gitlab_chart_version: "{{ dependabot_gitlab.chart.version | default(dependabot_gitlab_defaults.chart.version) }}"
    dependabot_gitlab_k8s_name: "{{ dependabot_gitlab.k8s.name | default(dependabot_gitlab_defaults.k8s.name) }}"
    dependabot_gitlab_k8s_namespace: "{{ dependabot_gitlab.k8s.namespace | default(dependabot_gitlab_defaults.k8s.namespace) }}"
    dependabot_gitlab_helm_config: "{{ dependabot_gitlab.helm }}"

- name: Create Local Kubernetes Claim(s) for Dependabot
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default('gitlab-system') }}"
      spec:
        resources:
          requests:
            storage: "{{ item.value.capacity | default('10Gi') }}"
        accessModes:
          - "{{ item.value.accessMode | default('ReadWriteOnce') }}"
        volumeName: "{{ item.value.volume }}"
        storageClassName: local
    kubeconfig: /etc/kubeconfig
  loop: "{{ dependabot_gitlab.k8s.claims.local | default({}) |dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Install/Configure Dependabot via Helm
  kubernetes.core.helm:
    name: "{{ dependabot_gitlab_k8s_name }}"
    namespace: "{{ dependabot_gitlab_k8s_namespace }}"
    chart_repo_url: "{{ dependabot_gitlab_chart_url }}"
    chart_version: "{{ dependabot_gitlab_chart_version }}"
    chart_ref: "{{ dependabot_gitlab_chart_ref }}"
    release_values: "{{ dependabot_gitlab_helm_config }}"
    create_namespace: true
    kubeconfig: /etc/kubeconfig
