- name: Synology Backup - Merge Variables
  ansible.builtin.set_fact:
    synology_backup_vars: |
      {{ lookup('community.general.merge_variables',
                '_synology_backup',
                initial_value=synology_backup_defaults,
                pattern_type='suffix') }}

- name: Synology Backup - Set Derived Facts (1 of 2)
  ansible.builtin.set_fact:
    synology_backup_package_filename: |
      {{ synology_backup_vars.file_prefix }}-{{ synology_backup_vars.build }}.x86_64.deb

- name: Synology Backup - Set Derived Facts (2 of 2)
  ansible.builtin.set_fact:
    synology_backup_client_url: |
      {{ synology_backup_vars.url_prefix }}/{{ synology_backup_vars.version }}/Ubuntu/Installer/{{ synology_backup_package_filename }}

- name: Synology Backup - Ensure Download Path
  ansible.builtin.file:
    path: "{{ synology_backup_vars.download_path }}"
    state: directory
    mode: "0755"

- name: Synology Backup - Download Package
  ansible.builtin.get_url:
    url: "{{ synology_backup_client_url }}"
    dest: "{{ synology_backup_vars.download_path }}/{{ synology_backup_package_filename }}"
    mode: "0444"
