- name: Install Cert Manager Issuer
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: cert-manager.io/v1
      kind: "{{ certmanager.issuer.type | default('ClusterIssuer') }}"
      metadata:
        name: "{{ certmanager.issuer.name }}"
        namespace: "{{ certmanager.issuer.namespace | default('infrastructure') }}"
      spec:
        acme:
          email: "{{ lookup('ansible.builtin.vars', 'secrets').email }}"
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: "{{ certmanager.issuer.name }}-cluster-issuer"
          solvers:
            - dns01:
                route53:
                  hostedZoneID: "{{ secrets.aws.route53.zoneId }}"
                  region: "{{ secrets.aws.route53.region | default('us-east-1') }}"
                  accessKeyIDSecretRef:
                    name: aws
                    key: username
                  secretAccessKeySecretRef:
                    name: aws
                    key: password
    kubeconfig: /etc/kubeconfig
