# code: language=ansible
- name: Configure CoreDNS to Use Local Nameserver
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns-custom
        namespace: kube-system
      data:
        lan.server: |
          {{ lookup('ansible.builtin.vars', 'lan').domain }}:53 {
              errors
              forward . {{ lookup('ansible.builtin.vars', 'lan').ip.nameserver }}
          }
    kubeconfig: "{{ k8s_ecosystem_vars.inherited.kubeconfig }}"
  register: k8s_ecosystem_coredns_custom

- name: Perform a Rolling Restart of CoreDNS pods
  ansible.builtin.command:
    cmd:
      kubectl --kubeconfig  {{ k8s_ecosystem_vars.inherited.kubeconfig }}
              --namespace   kube-system
              rollout
              restart
              deployment/coredns
  changed_when: k8s_ecosystem_coredns_custom.changed
  when: k8s_ecosystem_coredns_custom.changed
