- name: Create Kubernetes Secrets
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: "{{ item.value.type | default('Opaque') }}"
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default('infrastructure') | lower }}"
      stringData: "{{ item.value.stringData }}"
    kubeconfig: /etc/kubeconfig
  when: "'stringData' in item.value"
  loop: "{{ secrets.k8s.string | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create Extra Kubernetes Secrets
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: "{{ item.value.type | default('Opaque') }}"
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default('infrastructure') | lower }}"
      stringData: "{{ item.value.stringData }}"
    kubeconfig: /etc/kubeconfig
  when: "'stringData' in item.value"
  loop: "{{ extra_secrets.k8s | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create GitLab Image Pull Secret File
  ansible.builtin.template:
    src: docker-config.j2.json
    dest: /var/lib/ansible/k8s.d/gitlab-image-pull-secret.yaml
  when: secrets.k8s is defined and 'image_pull' in secrets.k8s

- name: Create GitLab Image Pull Secret
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: gitlab-image-pull
        namespace: infrastructure
      data:
        .dockerconfigjson: "{{ lookup('ansible.builtin.file', '/var/lib/ansible/k8s.d/gitlab-image-pull-secret.yaml') | b64encode }}"
    kubeconfig: /etc/kubeconfig


- name: Create Extra Kubernetes Image Pull Secret
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: gitlab-image-pull
        namespace: "{{ item }}"
      data:
        .dockerconfigjson: "{{ lookup('ansible.builtin.file', '/var/lib/ansible/k8s.d/gitlab-image-pull-secret.yaml') | b64encode }}"
    kubeconfig: /etc/kubeconfig
  loop: "{{ extra.k8s.namespaces }}"
  loop_control:
    label: "{{ item }}"
  when: extra.k8s is defined and 'namespaces' in extra.k8s
