- name: Install Kubernetes Secrets
  include_tasks: k8s-secrets.yaml

- name: Install Additional Helm Applications
  import_tasks: helm-applications.yaml
  when: applications is defined

- name: Install Storage Configuration
  import_tasks: storage.yaml
  when: storage_classes is defined

- name: Configure Metal Load Balancer
  import_tasks: metal-lb.yaml
  when: extra is defined and 'metal' in extra

- name: Configure Cert Manager
  import_tasks: cert-manager.yaml

- name: Install Elasticsearch Operator
  import_tasks: elasticsearch-operator.yaml
  when: elasticsearch is defined
