# code: language=ansible
- name: Merge K8S Ecosystem Variables
  ansible.builtin.set_fact:
    k8s_ecosystem_vars: |
      {{ lookup('community.general.merge_variables',
                '_k8s_ecosystem',
                initial_value=k8s_ecosystem_defaults,
                pattern_type='suffix') }}

- name: Set K8S Ecosystem Environment
  ansible.builtin.copy:
    dest: "{{ k8s_ecosystem_vars.global.env }}"
    content: |
      export KUBECONFIG={{ k8s_ecosystem_vars.global.kubeconfig }}
    mode: "{{ k8s_ecosystem_vars.global.mode }}"

- name: K8S Ecosystem Role Prerequisites
  ansible.builtin.file:
    path: "{{  k8s_ecosystem_vars.global.downloads }}"
    state: directory
    owner: "{{  k8s_ecosystem_vars.global.owner }}"
    group: "{{  k8s_ecosystem_vars.global.group }}"
    mode: "{{  k8s_ecosystem_vars.global.mode }}"

- name: Configure k8s Namespaces
  ansible.builtin.include_tasks: namespaces.yaml
  tags:
    - k8s
    - namespace
    - ns

- name: Configure k8s CSI Driver for SMB
  ansible.builtin.include_tasks: csi-driver-smb.yaml
  tags:
    - k8s
    - smb
    - storage
  when: k8s_engine.needs.smb_driver | default(true)

- name: Configure k8s Storage
  ansible.builtin.include_tasks: storage.yaml
  tags:
    - k8s
    - pv
    - storage

- name: Configure k8s Secrets
  ansible.builtin.include_tasks: secrets.yaml
  tags:
    - k8s
    - secret

- name: Install Sealed Secrets Controller
  ansible.builtin.include_tasks: sealed-secrets.yaml
  tags:
    - k8s
    - sealed-secrets
    - secrets

- name: Configure k8s Certificate Manager
  ansible.builtin.include_tasks: cert-manager.yaml
  tags:
    - cert
    - certs
    - k8s
  when: k8s_engine.needs.cert_manager | default(true)

- name: Configure k8s Certificates
  ansible.builtin.include_tasks: certificates.yaml
  tags:
    - cert
    - certs
    - k8s

- name: Configure MetalLB
  ansible.builtin.import_tasks: metal-lb.yaml
  tags:
    - metal
    - metal-lb
