# code: language=ansible
- name: MetalLB - Install/Configure Using Helm
  kubernetes.core.helm:
    name: "{{ k8s_ecosystem_vars.metallb.name | default('metallb') }}"
    namespace: "{{ k8s_ecosystem_vars.metallb.namespace | default('metallb-system') }}"
    chart_repo_url: "{{ k8s_ecosystem_vars.metallb.chart.url }}"
    chart_version: "{{ k8s_ecosystem_vars.metallb.chart.version }}"
    chart_ref: "{{ k8s_ecosystem_vars.metallb.chart.ref | default('metallb') }}"
    release_values: "{{ k8s_ecosystem_vars.metallb.chart.helm_values }}"
    create_namespace: true
    kubeconfig: "{{ k8s_ecosystem_vars.global.kubeconfig }}"
    wait: true
  timeout: 120
  when: k8s_engine.needs.metallb

- name: MetalLB - Create IP Address Pools
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: metal-lb-address-pool
        namespace: "{{ k8s_ecosystem_vars.metallb.namespace | default('metallb-system') }}"
      spec:
        addresses: "{{ k8s_ecosystem_vars.metallb.pool }}"
        autoAssign: true
    kubeconfig: "{{ k8s_ecosystem_vars.global.kubeconfig }}"
  when: k8s_ecosystem_vars.metallb.pool | length > 0

- name: MetalLB - Create L2 Advertisement Metal
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: metal-lb-l2-advertisement
        namespace: "{{ k8s_ecosystem_vars.metallb.namespace | default('metallb-system') }}"
      spec:
        ipAddressPools:
          - metal-lb-address-pool
    kubeconfig: "{{ k8s_ecosystem_vars.global.kubeconfig }}"
  when: k8s_ecosystem_vars.metallb.pool | length > 0
