# code: language=ansible
- name: Create Parent Directory for Kubernetes StringData Secrets
  ansible.builtin.file:
    path: "{{ k8s_ecosystem_vars.inherited.working }}"
    state: directory
    mode: "{{ k8s_ecosystem_vars.inherited.mode }}"

- name: Create Kubernetes StringData Secrets
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      kind: Secret
      apiVersion: v1
      type: "{{ item.value.type | default('Opaque') }}"
      metadata:
        name: "{{ item.key }}"
        namespace: "{{ item.value.namespace | default(k8s_ecosystem_vars.inherited.namespace) | lower }}"
      stringData: "{{ item.value.stringData }}"
    kubeconfig: "{{ k8s_ecosystem_vars.inherited.kubeconfig }}"
  when: "'stringData' in item.value"
  loop: "{{ k8s_ecosystem_vars.secrets | dict2items }}"
  loop_control:
    label: "{{ item.value.namespace | default(k8s_secrets_vars.namespace) | lower }}.{{ item.key }}"
