helm_applications_defaults:
  - name: cert-manager
    value:
      namespace: infrastructure
      url: https://charts.jetstack.io
      ref: cert-manager
      version: v1.19.2
      helm_values:
        crds:
          enabled: true

  - name: csi-driver
    value:
      namespace: infrastructure
      url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      ref: csi-driver-smb
      version: v1.17.0
      helm_values: {}

  - name: metal-lb
    value:
      namespace: infrastructure
      url: https://metallb.github.io/metallb
      ref: metallb
      version: v0.14.9
      helm_values:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

  - name: mysql-operator
    value:
      namespace: infrastructure
      url: https://mysql.github.io/mysql-operator
      ref: mysql-operator
      version: 2.2.6
      helm_values: {}

  - name: nfs-subdir-external-provisioner
    value:
      namespace: infrastructure
      url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      ref: nfs-subdir-external-provisioner
      version: 4.0.18
      helm_values:
        nfs:
          server: "{{ lookup('ansible.builtin.vars', 'nfs').host }}"
          path: /volume2/kubernetes

  - name: sealed-secrets
    value:
      namespace: infrastructure
      url:  https://bitnami-labs.github.io/sealed-secrets
      version: 2.17.9
      ref: sealed-secrets
      helm_values: {}
