helm_applications_defaults:
  - name: metal-lb
    value:
      namespace: infrastructure
      url: https://metallb.github.io/metallb
      ref: metallb
      version: v0.14.9
      helm_values:
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

  # NOTE: The 2.2.6 version of the MySQL operator has been removed from the
  #       Oracle helm repository.  BUT, the 2.2.7 version fails because the
  #       images don't exist in the Oracle container registry (at least as of
  #       2026-01).
  #
  # Disabling for now
  # - name: mysql-operator
  #   value:
  #     namespace: infrastructure
  #     url: https://mysql.github.io/mysql-operator
  #     ref: mysql-operator
  #     version: 2.2.6
  #     helm_values: {}

  - name: nfs-subdir-external-provisioner
    value:
      namespace: infrastructure
      url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      ref: nfs-subdir-external-provisioner
      version: 4.0.18
      helm_values:
        nfs:
          server: "{{ lookup('ansible.builtin.vars', 'nfs').host }}"
          path: /volume2/kubernetes

  - name: sealed-secrets
    value:
      namespace: infrastructure
      url:  https://bitnami-labs.github.io/sealed-secrets
      version: 2.17.9
      ref: sealed-secrets
      helm_values: {}
