# code: language=ansible
all_common:

  # --------------------------------------------------------------------------
  # /etc/profile.d environment files
  profile_d:
    gitlab:
      GITLAB_URL: "https://{{ lookup('ansible.builtin.vars', 'lan').fqdn.gitlab }}"
      CI_API_V4_URL: "https://{{ lookup('ansible.builtin.vars', 'lan').fqdn.gitlab }}/api/v4"
      CI_REGISTRY: "{{ lookup('ansible.builtin.vars', 'lan').fqdn.registry }}"


  # --------------------------------------------------------------------------
  # fstab (i.e., filesystem table)
  fstab:
    smb:
      host: "{{ lookup('ansible.builtin.vars', 'lan').ip.smb }}"
      opts: username={{ lookup('ansible.builtin.vars', 'secrets_vault').smb.username }},password={{ lookup('ansible.builtin.vars', 'secrets_vault').smb.password }} # noqa: yaml[line-length]
      mounts:
        homes:
          path: nas-homes
        kubernetes:
          path: nas-kubernetes


  # --------------------------------------------------------------------------
  # Name resolution/DNS
  resolve:
    domain: "{{ lookup('ansible.builtin.vars', 'lan').domain }}"
    nameservers:
      - "{{ lookup('ansible.builtin.vars', 'lan').ip.nameserver }}"
