- name: ArgoCD CLI - Merge Variables
  ansible.builtin.set_fact:
    argocd_cli_vars: |
      {{ lookup('community.general.merge_variables',
                '_argocd_cli',
                initial_value=argocd_cli_defaults,
                pattern_type='suffix') }}

- name: ArgoCD CLI - Set Derived Facts (1 of 2)
  ansible.builtin.set_fact:
    argocd_cli_system: "{{ ansible_system | lower }}"
    argocd_cli_arch: "{{ ansible_local['dpkg']['arch'] }}"

- name: ArgoCD CLI - Set Derived Facts (2 of 2)
  ansible.builtin.set_fact:
    argocd_cli_url: "{{ argocd_cli_vars.url_prefix }}/{{ argocd_cli_vars.version }}/argocd-{{ argocd_cli_system }}-{{ argocd_cli_arch }}"
    argocd_cli_download_path: "{{ argocd_cli_vars.paths.download }}/argocd-{{ argocd_cli_vars.version }}"
    argocd_cli_download_file: "argcd-{{ argocd_cli_system }}-{{ argocd_cli_arch }}"

- name: ArgoCD CLI - Ensure Download Path
  ansible.builtin.file:
    name: "{{ argocd_cli_vars.paths.download }}"
    state: directory
    mode: a=rX

- name: ArgoCD CLI - Download ArgoCD CLI
  ansible.builtin.get_url:
    url: "{{ argocd_cli_url }}"
    dest: "{{ argocd_cli_vars.paths.download }}/{{ argocd_cli_download_file }}"
    mode: a=rx

- name: ArgoCD CLI - Link ArgoCD CLI
  ansible.builtin.file:
    src: "{{ argocd_cli_vars.paths.download }}/{{ argocd_cli_download_file }}"
    dest: "{{ argocd_cli_vars.paths.bin }}"
    state: link
